apiVersion: apps/v1
kind: Deployment
metadata:
    name: tachidesk-deployment # <--- change this
    namespace: piracy
    labels:
        app: tachidesk # <--- change this to match label on the pod
spec:
    replicas: 0
    selector:
        matchLabels:
            app: tachidesk # <--- change this to match label on the pod
    template:
        metadata:
            labels:
                app: tachidesk
        spec:
            dnsPolicy: "None"
            dnsConfig:
                nameservers:
                    - 1.1.1.1
            containers:
                - name: tachidesk
                  image: ghcr.io/suwayomi/tachidesk:stable
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 4567
                        protocol: TCP
                  volumeMounts:
                      - name: data
                        mountPath: /home/suwayomi/.local/share/Tachidesk
                  resources:
                      requests:
                          memory: 128Mi
                          cpu: 100m
                      limits:
                          memory: 1Gi
                          cpu: 100m
            volumes:
                - name: data
                  hostPath:
                      path: /docker/tachidesk
                      type: Directory
            nodeSelector:
                kubernetes.io/hostname: "ovh02"

---
kind: Service
apiVersion: v1
metadata:
  name: tachidesk
  namespace: piracy
spec:
  type: NodePort

  selector:
    app: tachidesk

  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
      name: tachidesk


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tachidesk
  namespace: piracy
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`tachidesk.adriangonzalezbarbosa.eu`)
      services:
        - name: tachidesk
          port: 4567
  tls:
      secretName: tachidesk.adriangonzalezbarbosa.eu

# letsencrypt-cert.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tachidesk.adriangonzalezbarbosa.eu
  namespace: piracy
spec:
  dnsNames:
    - tachidesk.adriangonzalezbarbosa.eu
  secretName: tachidesk.adriangonzalezbarbosa.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer