---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: dawarich
  namespace: dawarich
spec:
  encryptedData:
    databasePassword: AgAjHu96hD0Rz4pa1cVy5L65pMAO5WW1xsGa1jn05NUbfjl+WuJouK8aMNKM/iZobPon2pvQmrMZuE+Xg1ECgeFJMLLeUbfc0kQqHHkhMQDXd7Cm/L/S7aOErRMGHa423rtcSLc4DyLvBWorEqxEij1IV0ORho5zghSONWt5RBOVj4I2Am/INpzEoupm5la1a1zjtQPDuv7vFMTZ8459gi+vI+ojCBshw4xYc1OVwiaKHG2tjk48Rg5CbJ52SNHy8RmisLLWXDxkmOlU7/71C3icul/0xy2tcvfLOa7J+fKed6NtKiPy9ecxYM4ggJIGPuKaRZUPFbzKaH2iZkZU4O7YRQjyi1jbETnohbtIc90p5vJAV1+QvYdrj3hTbhgfvyb5Bv4bWL0lDlzR2m4nYUdaA42+EjrcmaYAz/GopaIiLM2akAaawYy7J2pXKD+uOjx2hKrK36qcqpyfZpZBOjaQcrevHwiDz82hYg3Yk56226tYXy7hLoNtrcXUpEshdpa1+zvxDyvwbFmPArnySzeG8wV+/x5jIp6zegHX3zdTiUvcFCj+FO/7z10WTM0Ujzpt+ZLdpoK8/qcR2pWJ9JkheAvwInTcspkjzUNlHHtZE2bUN5rERxZSCemCTSjDHgeoSPw89sNIpc9pB0x+cy0AzBLwRv4ZDi29WGzUN2RQeGLECWrf9Bcso4rF8guk8typl3HO67TPG09xP9GyVQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: dawarich
      namespace: dawarich
    type: Opaque
