apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server 
  template:
    metadata:
      labels:
        app: server 
    spec:
      containers:
        - image: ghcr.io/immich-app/immich-server:release
          name: server 
          command: ["/bin/sh"]
          args: ["./start-server.sh"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: dbHost
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: dbPassword
            - name: DB_DATABASE_NAME
              value: "immich"
            - name: REDIS_HOSTNAME
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: LOG_LEVEL
              value: "simple"
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: typesenseApiKey
            - name: REVERSE_GEOCODING_PRECISION
              value: "1"
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
              value: "Backup de fotos de LAMG"
            - name: IMMICH_WEB_URL
              value: "http://web:3000"
            - name: IMMICH_SERVER_URL
              value: "http://server:3001"
            - name: IMMICH_MACHINE_LEARNING_URL 
              value: "http://machine-learning:3003"
            - name: ENABLE_MAPBOX
              value: "false"
            - name: MACHINE_LEARNING_PORT
              value: "3003"
            - name: SERVER_PORT
              value: "3001"
          ports:
            - containerPort: 3001
              name: server 
              protocol: TCP
          volumeMounts:
            - name: upload
              mountPath: /usr/src/app/upload
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
      volumes:
        - name: upload
          nfs:
            server: nas00
            path: /mnt/RAID/docker/immich/upload
      nodeSelector:
        svccontroller.k3s.cattle.io/lbpool: lamg

---
kind: Service
apiVersion: v1
metadata:
  name: server 
  namespace: immich
  labels:
    svccontroller.k3s.cattle.io/lbpool: immich
spec:
  type: LoadBalancer

  selector:
    app: server 

  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: server



