---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: vault-mcp-git
  namespace: knowledge
spec:
  encryptedData:
    token: AgCEYNZgtGmQ3nyx0kIlMA1WbyplhccVSHfKGHPAd8lnJI4I66aIVfsF+z2jO3BuMpktq8HoJKc3DpxzyX7xkhD3DP98Wasf8IdPE2ts7sgfy5kajStcMNZ6/JhQGAzukPtT7e0DJEvVugWdUEsyqG0ng7Kw7eBh1cAgRBBMkSfzRyaoYAeWWY8+4d0kFKJ+VDSaTSA5+qTiAuqIoDMZO4OaiKgpsQwcm7GJ3I3ykP7ek8cH+DwzGpOozPrik9+Dd29rxdvgryYBhgU7JyFG0w6U/NLRSEgUd/tEIBSZtyfRRVIeQU8zuefX+sO8gWCFVKFfAuM7WJvNVlmdk+0DK2qIuVTz6l81kw1+iDnRyrIcB2MxXhTstrUnjcLv2yOl33AQpnUTrYSX9B1ITN3f/XaF4b1o/FO2QeBbgv/IqQ4STNyQHt29Q7b+8fy3pcv4L0IWZ/ihA7Xwm3NCvn+fuoQs6mpunVfKuUwGJ5Zh4TpRyBt0MCEPuF6D/G4xHEkKrgc4qYwFvcvZgh3sAL1IyFBvlMQ9VS50U9fjpdgEFWxH4SY/QJMEOWlhF2U/qg0J8v65hKBJGSlxizKr0+bxFrtZ4596YPb+BSHXjEbNAfL0Q63WDL4NHvBrgb955rRGYrgB22QTbOsjHdVx11PGuaR3VFnMwg7iCllB7W5hMfKKjgw40TIKfSeijEK2uRP2CuP5yaDsPScXQPgyXz14Ycjxy8la7i5s7v8l4D+ntrFDmYSDitfZ6zp2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: vault-mcp-git
      namespace: knowledge
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tailscale-auth
  namespace: knowledge
spec:
  encryptedData:
    TS_AUTHKEY: AgAt2Ju7HNifRk8E/PQLGAmm3wEQuvE8J9HW9PM6ekpPAuyoHZ8wuwu+S6aHWJJVMH825yHdvqJgR/3zI4wtnOcCKdE7ixIecVvCuRQQGwUG3omwQwIjNFbD3hXlVQkynLTTuqSF5xlte0maE8TW9G5eGshcq6qTmDxR1HJWquHU7OXYlBSo1F/b3EkoMmrabm+25besEo2Zf0DqfFDqKjn0jDlYKQXWI497JI4hebDKhOo8RRwgkhsy3f7H7DVzYqw5WDEuZqBFkFUFA+mk5Iy6iJJgByUSUxjys/WA6K4FdFXaVG1K8mp6+iDa3qTcepxnxgiuFUICLpGsHVM9kEpOiGcSRq9ewPwxPh1kwtKZqdFXP0bX66NOlbKI/tw37PvVHFIgxLVelC+0npy5vW8S2TsL3XyInFK/f9YO0dAMenR0UGPEvZDc49tG0P0LYRxkaWUlMIW92TgXMSrru7LS7ZBhHFkiHKYM1KLtZMXm97ESoo8zYjeSij0ZgasfzAgxwKiyLJaHrJgA+MRxl2tRuSMpVPTKHzeAp/o6b0FEPSho+KP/liXJHXI7g1N0tXWIZZ/A3qoDnHZrVcto/DoY0c783DlPqw9CzeFx+fYp/C15IP9BJPeJJjQ7lOZ6pk63hUtOVffO0XsCAFxburLIMxNIxU6sRcR3/ZU22yfudol96szQ82ocnTnzRvDgAd8fH6O4EwVX5un19XnZE3F9saxpzaleJF1ZbsM7HjkDLae9+bQa/QfqmprY27vzrI20ryjn9bNSEJ8Tx1w2V29BRPWecDlDuZgseSsO76LmHGBpgDb+/Km1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: tailscale-auth
      namespace: knowledge
    type: Opaque
