---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: vault-mcp-git
  namespace: knowledge
spec:
  encryptedData:
    token: AgBTjVDo9iEG2jcrLTG5UXAskgL6tNj35d1hqZkPe2dCRG8qjxOPVAsYmjrRbgxhjdiD9LJmvffwtaExrLixc3hFa2Hb9770HIomLrqhCwyr+S0UHlxjnNLTs6h7ThQZg9eT3AAQ6NmWwbIy+PyDnF2sbLwADXKZCdSnRY1t4E5Mv1Oh+NAGYoRa9pF0eMjiYOIYSTulFxnwBBA5+ZNhZzxtzmyu55DaCQo3uMvmX9LmfQ2PoaaBKqZ+/xcpOJ/wjH8Vfe9XkZ5coL0sQsWeuGLxOKqGj9CTjWi+8B+bSQ2OP9LIiC4eDp/FyYg/vnir/FueoH6AbSWP/CB6WmqS57/+djlam0hNjBVis36yA4N5jzsIVuDN8kKGY/IvhKVQMHQwombOMV8nL10a7679AI/1WRiE9qqOFWvj3/XR2qF6FQ9X+cJH7q4igjR2LVd07yuArUdW+eQZPQDxbN2XvY6ZhTnnPg4xkJ6pzCuepf3NrXMNpKIIQA2DxX+gtHuUVIX6LxexfsMnvs7EkA2mXbSrSV5FTUmdO+H2RveLPxGG4gnnW6/hpkfsv7kp88ovV7UG8dsVSOOTY9QrQsrXkN7am1FgRmKR2bPLy0hY025tucRj83cqLwMAq+SnJzaJUEa9qkYQcW7IDoont+Gowl9rcYBe6gsGbg191H2wNadOx8j5FCRfiNgbE+jQiI8L7ZoGvD624M/sfNt+3QFLYWuKju+bulAU2djuCAbVUvn4BD3/YbgfCZ9w
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: vault-mcp-git
      namespace: knowledge
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tailscale-auth
  namespace: knowledge
spec:
  encryptedData:
    TS_AUTHKEY: AgBYKprl8iV52buJXvF58P7c8KovZazXFzgg0R2CcGf+KEg1MyW1Sm/WAbNw8yEdpG3e13op7yCbgaD9yzsM+RPswXBY38jSQI6tdX3al3SY+XWCRxXaW2I/BNEXxw7HWcQw8XW3YQlsixQA6DlKAEam62SvwJTWBQDiu21YC4Hwl0hVgMxA9eYqBuzvQTec/oCyt68/VAxIwO4+JziCvztFQhVJDdEh5kw/uPQIl/O1OhxKP72dKLL5XQm9yu0jjkU/87CtreVfxgkGUyiwDTfFh4qGvTIxpBscz6Of/xN20Z4O2rrsK+YhZcx4X+BeDMv/QR/iagOOHIxdVIPRicnwQqHBM8fxyTILfVZbb86li5daUhaDbYBMa2AGA/tkEog25WNxNWoBIMsDlX/o71zzJJJy5H9HTZ+uUIZU3Q2U3ekEPPimomMIZGJtkUeoInBiDlqNkM0XMFMNGV7oCtxfbbK7f+oWLqGSED4Czgi1Lel4bBw217Epb5+5uzONukfwh9g5RxfnopqqjLfuK8vTeamV61hwMT7brYDIb1eJ+eMX7z5tjhzdbfWJFxHLVW08K6z729idzNqU5ooueWnCXSMs1NJug2xETLA6ppvTZXJ7okFh9Ge3NZJQJ9an5T/dVvTu7hiSVyhA7UTwfXMByhRtUx4IgBxXxUNurOYvrDfN6TwiMPapS8ZIy2mh7NQBpEuIYBI7IJNrXois12sNC8wsn9aEJkHp+VZXm5fdk7kQERexVZvhKDfMspgqi+RFy60wSHWRCiKOFVNljeSPDKUG9Lbtq8J+geMBvai41r53qnPtvlFr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: tailscale-auth
      namespace: knowledge
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: vault-mcp-auth
  namespace: knowledge
spec:
  encryptedData:
    bearer-token: AgBekWn+Ggc44Wo9dTf0UBv2oKGUQt4aYduMBe/RELipNt92rkAGL245enjnRoX5m+2b7MPnQC/R1zT0MIZNnzHEhP4fmD/KoRFA8kBuyEYC2nekC/P97+vLcj/aPegh5YZgQq3u95s64GGCZ2OcAOzDfRKNxwjaAxlUMI7+6CvsmUzAAV85aBQrvObD08hfXz8Cn41TGiHBSksBNSFdwtGkZojAOBpA+GjaJiiGiLldY7LUyx+mcai3JArOdrPIK1bFOmflwvAr+hPmIrKdtEx1sbnJ3xSM2v4iZYXfnAEG/zk3fU+LR3TEqE6il74ZKBGKGRAAwzq3GHy9W8BoI5ieatGhhsNhwsCi0s0PUhR/D33ylYH0eFi9k883zyxtTHt1MZqtyIVCVk3K3aQ49oDQGYbAVWzFK1BI3UJM9vsO0fRxspC7dGAEPHpe3pZX7jq+cYt6Z4Nnwft3rFXHlL9bWbcJc0jUDLp/koy15k/8maDVTu/AzswdatE2HbazJNnHHk2DWDyTnffrbXDjftRlOrW3H7LMmrNbs/g7geNhRGI+0V+G2fd9RsRr5f7lz1rOzhodEsuljeSJbdsVkQ89N7dFvLzQXKN5R/Hn6jJ4nZ5GOv2/yQhSgFjPOOZiOJfF1f4RXXfo/e6Zq8ijaZL+HqkCgyBiBbQu2GAPveZgRi5itfDu2j58HEyLwFUcj899smwJrx/iW64rGPvViMdcnMXFMqbGL0SrU+7/OhW0EbqaQuSYumWTyqXCJCT+/dDzM375nBbFDtaGf5lsPhFj
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: vault-mcp-auth
      namespace: knowledge
    type: Opaque
