---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: games
  namespace: games
spec:
  encryptedData:
    factorioPassword: AgBlXXssdA8lu2lvwJJl37wyybut2KA/ly2XPFILnOIn/SWV1+rKg/8349kr6TMBlrFy5IqR7KHhnQXLvRHH5QpgOfciHxpEj33XHU5BZNTnDREqa21a+R7oZYLFM3jm+Xemhc23sFXT3VMtxRThXoFMHEjn34nYzFswfeFb4tS1NAlyhdFSk78HLyXbDW2OokvRXYxQhpawIxkkCxxxyX2dAnZPOvVJhvO1JfhWUABFgNgZtxsD9BzqxS7lRGInbICJ9heA5Vclr34tPDg1Y0t8t+hko+gzHBPjHbTBbSt/LIGxRwoZgwDDDAEK5z6x4zz2JPXLJ6kJDjHq7faJVg0L0b0Z3UFm9Fu8ZeU0UHcS59aYRFvcBirEkqpizyA1iKr8Lu4vDKVkIjOCu/QYLbUHCaw6VucvPuSt4uUOFtMubLylLu4QwsiS1uHcpRlZfXa/4pt71y64J5txts71jpVg9iqZqopGUNTTAtpJxt+fFd8k49qQVwoYst035yCOTBrSkRNZZrLvCnb1PMHWrposWQEFj+kHlX569om4ILniepJFRcnWTBin329xgA67yv/DsuFRv3s3WDgLuT1zz1QYr17/7rZi8heh0LjfsqjC4ArYvJ7xXTLErFgmPzpQhg9IjGZUCkDv7zlWusX+r75QF5r8x41/OqXO1c6fKhT81jTkVz6Z2s8p69TRF+40qX3fwZb0cAjFF+Cbl6tOeA==
    factorioUser: AgBEr8V60gBht787KxP3ngBrucRKa7b9Yhmd7xuEcnLR6J0TzIzY449j0nEaUXQu89q5QWwu7JGJJ4uANRTE/gI8NF4bVWYVX/BMxYHCBi/DQqkauPBn+pqdqwuaidRdfU+IDi44fFQLao+XrfS1D8s6MNZrGsI+ImCxqGhfK7eQ2BHqXXs5zUQU2JYLiktJOey/7xZPkhEdbRhHz5E4qfRrjUtJIOaJp2erBv+yeT5wkWVJeXCudf7aOPbQn8Tl0WzyVEhtYOJvFT89R4ycCAAfHlSHnKQEixKEkTimU0N9EIG3RrMlQamsPxt5xuXBiqcEUQ62wiGnLJ69rwZhLF9OoK7xi2lHJNJ2O4qO9JZEhRa/f+KaUuz/Q4ESLs70TaU25BGWmQR4AD4OraJB/E+VJkjd96TmlZ8gK+3pH+pwpmV1CY9hy0bab2/JWk1IO4QzoargYxwg1cIsFr4WqqEBTQupxhgqXQ2VPLq0j8rzbADIvTGtjwt/KauqCyn5ERFqn3eLaamgB8HzGk4uKTsiTBVwsZeDabB3PErRBVrADHKh7JuNhiZXaQ3GUQLouRr6NWlZ1BBjN1WI5IV9eODzrqvsgu/MlWVsDk3DYnCgr0sNrLsyPbWzyMlqheaWPIHOnsejRcr8gkRzZ4dVItnGUW/56p4v6r4cl9FRWMSGhTZutdrgs4ogyL9O3eC+LG+MBY4rdhzJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: games
      namespace: games
    type: Opaque
