---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: trek
  namespace: trek
spec:
  encryptedData:
    encryptionKey: AgC01aZsfVWuDacERuQTMaf/HoSp052g3Qm+pOQFngphfBeP5vW2UWXXXejkEoTsmlK01YEmXaSLcJEBbO1I6eUbrS8fhl56D2+Br8Ky4qu20D7gnIxnU24J2bGn3eWZgYBtAezJ/GdnfI3/YhPLTO8f23uG0lJ3K5PiI+Dli9lo5v3leygpQdW/aEW1AR7HF4WWlaEG0clSjdscpcJiFAHRejvkcDPtXF+KGhYB+bylBMX9Ex/WYIwtIiO9DXxQ+KUQYbrGDRmbd19s1YN1ugdAkAtNEQ3IyzKpxtA/d+4EW5+ve4E3ZY1UfVWpjuNKPko9u52CqQSbmJpcwpDrpgfoIokNUzwvpe+GV5mC53m6hBtZ31MGIOeEwM4EbJwJ+mdwfmjyxiPCeTH9BK3dvTEjgGEK93jcYW4YKEtOwhN1otNDX+rai1bMSnIR2v+eFndpwiiTt5XUrb0DYGqGOvBJAfC7IRblCXG80GEY4XNNiOPINc3Qb5f23TB1TCzBqxAnYAp5l+GKbhE9sRY6ezGGpJjKd7rhMI1ixX1Y3oxXgrnRnhP3kLhpdQwkD0xJNTMhRf6kX5QCaF6xRmX9pB7MMykJ289QpExi2gvT3FrDcnbZxaOuVm+SrCoCxrU/5S4PGMJLLMjaGo9p2cmWBJPmo5OcX2xvL70vCHPxri2jiU+wepjCdU3UsiL1e8cN3akpU+M1zcx6nnzvC8sqby3mAoemIU1HHeKtqAITdF2srDSfD5BFBqPX/epmfeSTjq7qw1i8QvGTeXUSwuqlfwQt
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: trek
      namespace: trek
    type: Opaque
