apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netbootxyz
  name: netbootxyz
  namespace: lamg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbootxyz
  template:
    metadata:
      labels:
        app: netbootxyz
    spec:
      containers:
        - image: lscr.io/linuxserver/netbootxyz:latest
          name: netbootxyz
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          ports:
            - containerPort: 69
              name: netbootxyz-1
              protocol: UDP
            - containerPort: 3000
              name: netbootxyz-2
              protocol: TCP
            - containerPort: 80
              name: netbootxyz-3
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: assets
              mountPath: /assets
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
      volumes:
        - name: config
          nfs:
              server: 192.168.0.24
              path: /mnt/RAID/docker/netbootxyz/config
        - name: assets
          nfs:
              server: 192.168.0.24
              path: /mnt/RAID/docker/netbootxyz/assets
      nodeSelector:
        svccontroller.k3s.cattle.io/lbpool: lamg

---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz
  namespace: lamg
  labels:
    svccontroller.k3s.cattle.io/lbpool: lamg
spec:
  type: LoadBalancer
  ports:
    - name: netbootxyz-1
      protocol: TCP
      port: 69
      targetPort: 69
    - name: netbootxyz-2
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: netbootxyz-3
      protocol: TCP
      port: 8088
      targetPort: 80
  selector:
    app: netbootxyz
