---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: lamg
  namespace: lamg
spec:
  encryptedData:
    plexClaim: AgAUkpzyD68EZOU2PkQVBOAeOE50MgH2Zfv+Sm1O2TeFExb1R/2bWFb4njVT02I0xiflwecvtduO+R5/vLAVWkgOLptT/UGcqJERT0d6U+wXqZ1nEEhomFqaH5Ru4qIqq3SWcfESTVOlzUtZT9B2wvaYY6dM4dU2hvtqh55S8iwXoG+bqIDDEXepttupYIa7hFs2im22npuW478H/SH18YCC1fp20xS20alvpg+p8+qj/4k/C6m32hVaJ3xCEyS+cKq4cQ+pN7lGKtE9vfxWjD4SoNDobdMtMZKsw7vqxdd/s1jiYfjrnw9kxC1NAcopSTkmSnCMAkSK6YyDJXceCdMlAUtmeSlZSUAEA1l2KPQq3xEJxd+MLLsDjofM3mRQpxp+g18SUChZMQ5Rnh/9CrpmsCBIIj2EZg9hf0jVwFhfjcafaX5jjwrDu3pNkAjmIiASxM/v/aUZRZdvYauYXgEhA33uzgcrYZXPOL3wA43nwVaLlgM2mrquDPXBs1tmFcWMI+ubO/kIeAfUyR6++fxAgQPiJm5FJTdkK/owrtZLljCDJPbDQw9J+Ao/LlnKCYfXwoecj7Z51uTsWX4WRLX0YjHNcEspxzOrifi4hWR+EFVz7dHDD6TaGNJTpwv2rn1pRhOeXLJqFPpG0HetMgMXmSnfYgivX2c/FQPj2/u9RJQrPrKsayH/LLHTVBiNkdNZhEMlF0ZKE8Gao5iCCJYe6u/EhmYbZG7hDw==
    sudoPassword: AgBI+0eWkgUCcLy8EdsNvx7TSwHqL1EDEFkILVGvzMZumCzvFak2In3SDLcR8d4vDHNw6m8Q+XFxlFj5ho4Fo+Ucgg9PbXyZ4fMm8/ixhJmQAvWVvWhWBaTWnQ6KXgd+M2CRQc/mjYrzi1AZqBfcZ6/5FZ2GZH9ZpiuKUhdFFEuq3NP1EQHerNArlkMFtjmWtuF21D2XYSP9WcMKeZj/Ah5qcG8xU7Kdxha+m5pio0Fyw5c/xmC1J25VVrpy68A/qrw7dmK9Yc531Z0yUaUKcgTea6fSwXG2I215CN+WShcQ+NMi6cIOSjtO9W1JzBvOwLfjylIyM6TOS8kODoI0leIJVn+ZQVy88jEA3ZLuG33k6FTG2ViiN8m3z0eYTibb01gcUB251FfvOwAgTSrQuCZT3WJY5kQdLXEc866GG64Zko9f8y4S4zIiz26e22unsh8ucuKAfhUJhslTtsZt0HC2IMS3bn6Wxcu1osgqT1cGtdCzjuU6rwpJIRQH0cdX6AbKQ+i2MAiLL8z4+Yg748Li39SySHd7jKhVXYfpoqBN+HWmox1Thuyz1kSVEmU0bdQ2zWCGssFDBg/boTafx+r9yNxm46mIMHgminklB73pC5TSeMaJvIp/K8p2cpG0jeXwoMFeEy+I3G/khmfS++5K7idL5hRrfq9OvO5Jabw/PCc7i56pXfto3Mja7Col5KhS+v1tFWky/uMPtDTWiOZ1h18iXiA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: lamg
      namespace: lamg
    type: Opaque
