---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: lamg
  namespace: lamg
spec:
  encryptedData:
    plexClaim: AgAUkpzyD68EZOU2PkQVBOAeOE50MgH2Zfv+Sm1O2TeFExb1R/2bWFb4njVT02I0xiflwecvtduO+R5/vLAVWkgOLptT/UGcqJERT0d6U+wXqZ1nEEhomFqaH5Ru4qIqq3SWcfESTVOlzUtZT9B2wvaYY6dM4dU2hvtqh55S8iwXoG+bqIDDEXepttupYIa7hFs2im22npuW478H/SH18YCC1fp20xS20alvpg+p8+qj/4k/C6m32hVaJ3xCEyS+cKq4cQ+pN7lGKtE9vfxWjD4SoNDobdMtMZKsw7vqxdd/s1jiYfjrnw9kxC1NAcopSTkmSnCMAkSK6YyDJXceCdMlAUtmeSlZSUAEA1l2KPQq3xEJxd+MLLsDjofM3mRQpxp+g18SUChZMQ5Rnh/9CrpmsCBIIj2EZg9hf0jVwFhfjcafaX5jjwrDu3pNkAjmIiASxM/v/aUZRZdvYauYXgEhA33uzgcrYZXPOL3wA43nwVaLlgM2mrquDPXBs1tmFcWMI+ubO/kIeAfUyR6++fxAgQPiJm5FJTdkK/owrtZLljCDJPbDQw9J+Ao/LlnKCYfXwoecj7Z51uTsWX4WRLX0YjHNcEspxzOrifi4hWR+EFVz7dHDD6TaGNJTpwv2rn1pRhOeXLJqFPpG0HetMgMXmSnfYgivX2c/FQPj2/u9RJQrPrKsayH/LLHTVBiNkdNZhEMlF0ZKE8Gao5iCCJYe6u/EhmYbZG7hDw==
    sudoPassword: AgBI+0eWkgUCcLy8EdsNvx7TSwHqL1EDEFkILVGvzMZumCzvFak2In3SDLcR8d4vDHNw6m8Q+XFxlFj5ho4Fo+Ucgg9PbXyZ4fMm8/ixhJmQAvWVvWhWBaTWnQ6KXgd+M2CRQc/mjYrzi1AZqBfcZ6/5FZ2GZH9ZpiuKUhdFFEuq3NP1EQHerNArlkMFtjmWtuF21D2XYSP9WcMKeZj/Ah5qcG8xU7Kdxha+m5pio0Fyw5c/xmC1J25VVrpy68A/qrw7dmK9Yc531Z0yUaUKcgTea6fSwXG2I215CN+WShcQ+NMi6cIOSjtO9W1JzBvOwLfjylIyM6TOS8kODoI0leIJVn+ZQVy88jEA3ZLuG33k6FTG2ViiN8m3z0eYTibb01gcUB251FfvOwAgTSrQuCZT3WJY5kQdLXEc866GG64Zko9f8y4S4zIiz26e22unsh8ucuKAfhUJhslTtsZt0HC2IMS3bn6Wxcu1osgqT1cGtdCzjuU6rwpJIRQH0cdX6AbKQ+i2MAiLL8z4+Yg748Li39SySHd7jKhVXYfpoqBN+HWmox1Thuyz1kSVEmU0bdQ2zWCGssFDBg/boTafx+r9yNxm46mIMHgminklB73pC5TSeMaJvIp/K8p2cpG0jeXwoMFeEy+I3G/khmfS++5K7idL5hRrfq9OvO5Jabw/PCc7i56pXfto3Mja7Col5KhS+v1tFWky/uMPtDTWiOZ1h18iXiA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: lamg
      namespace: lamg
    type: Opaque

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: herdr-authsecret
  namespace: lamg
spec:
  encryptedData:
    users: AgCgcIc0PpoyF2ef79TtyB0AkWsnyphG6+ey64NtT3J4idWinwCDY+F0PYXdInOSq6EP9dA66q7p82J7ctbBZtNlJFGDwzRZe0GJYbD/jn9kbrGlG33+HW6Cp/0ANgI/t+b9GIJb1CzU2NKpQal71LbSwcQLwWxRHjs+H4JoHZJjHWLOspve6VzaCfKBXQK9H4MBngPzRhmypzdBf7xY1fikWanVQiubWP7PW8ldHnYfnV2z/GHFpNT7/0WxAh2XSfFBoHpwO7a5DVXXc6VnnioBU65O8ObeTARCJ36zFoSmc8GHOLIyEbhaz7A5J/MHRAdGFfjley8TmhlZTOhXGW3g1I3SvQf7LbQdpuQzwmMmzPWa8t5/9rIBxQsHRB2m8Orl38wuZ1v1Ql0WOWN31+h1UPrfs7piPzSl12wq/wloyKO/q8J9s0hZwZUQGf+bnnIq1yueDhJxAiW0QIJTjwwvXmlTLhShykovoc1VMJoL3bOkjVP4R0CHE5jNb3pbRZ4829y10oKcNf/5L2MDI/TZixd2WiZX93pMq/tISjQUQOyGIt0EftyDXBmu383/UUGX0QqM74FXw5x8PXJb340PP3GNiL1rTAE3h9RTMm1yC0cSE/Cag3Td/2mjFHxPQ0PQhzfomdyvpofNGsDNum+BYxbZJpm3wAkE+ApfA0QO3YQ1k9lJ8G0+TfFp1Oy/k/ZVDZAAAT8LrUYclly/5FFq6WOCZ27aivztZPg/wUMRq1t3bb+td2+dSFgmDZAY/b2lHMLa7rBtuYTlcmYm3tSv5io=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: herdr-authsecret
      namespace: lamg
    type: Opaque

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: herdr-outpost
  namespace: lamg
spec:
  encryptedData:
    token: AgAhnDpmeldSAOmNfGoYBFolencqZIZp6z4p8fUtnCUuJLyJHyXNgJa1fa7B38oxucs/cK+a45pQUeOiCf9f1TKj4U3LJQitb1FPT5QArCGRvBrbXuaFsKFQ9pIwDg0OCUhr9WlQwutJSv6jh1AWRFuWqbKU5kg5avXvd8RCWbcTfGrBI/3OaBiirH5lPL/K8ZF+ZIVvxfjwErBjuJ6Y5Z3xXS6Sdmbx9+ju4WK42MM6dzcD92hhF/hSj8sFVYItmXm5NsnVYb3ee6wsuRB4BgEq6HqxS/7rSxzzig4Zb+nNs3+ErApFqMNIwcX8B+czkWEa2GGDurRAP4aXOiuVR4+YtIiLPhcf2zufVViG1naBSfsRf6uuxDZXDAXydQiqzQTTigCAWgqC3iVhN8LvXEJObXUYgBBJO0YI4x2Bc9Jw9e7i9cBz1IHv6JySxIqhEOC7Z1A6XTn61QTuA6XhRI4QqaURNim+9a4RLio9JeoisfV0I01yABJ6Y5sy1VcL1tFuiKz47vIk0kQYnPpOY3zNiPVDL1ZwPbwTe2q8AotgmL8g5Bkym4HGyXyudKgAEdVCZZU62mifLbhw0WofuImds8UdhT0hxzJNrBpfjM1egXX+erN1dPpJD1OJ2SPMkJYH3NC+cZl1PvrUwIq2WG/fikxzuOhx7ixaaXuUj9VlNdnQehYJwkyq7bNcYheAn2DhiHrmHiF0x8Ql4D57uS+1mqEg527WhjXRye9xWR7gaOL4mOksghCA+C4RkJlqWXE5A72rHJrkMyfZZV4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: herdr-outpost
      namespace: lamg
    type: Opaque
