---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tessera-turn
  namespace: tessera
spec:
  encryptedData:
    TURN_SECRET: AgACa5mJlJf6mVh6gVs/xKSgs1W0Ob38+f/O5pxGCra9XF8a6PZaMizhJ/beUY9c9sRKcf2r0iRhp/hWSB4+hxQXSqJiuBMdtIq81SLywzHlonmkpIXWVd5bUQ5+PgU2lWAgBoSa5xUUtViPTCe4AJZY/yX7rveaKIn+ZxUkLg7mmveiyeMwuT7FXSbBMht9R5UwDRD4gA9QCk95N+OWpcwxPQAoiOgvNsrGsLGTOEF9knxcYIHjOEo3ToFnAYbTtsD9nqvPmETqugm6TaFZ+EotBZrEJYUUdj/trOemDljPVn5OCjrIzduZ/FzQ2fYXcMQ9bRigRokOROHkq4PcG5iU59TpJOIanexZl9FQQEMLApMRBGjqVWrYf+HvEbpP36NqsAHDE53yskcQVUl6X7IbYLXQxAA3yX+cpZJMC01RMy8r4wNCf/tOGXmEobWmxrcUrNE4EWZxaADdbZgWpVhaV88cji2aX3+9TIZYvEr0vh6hGZYBHrnNl/X6eKF0g0P78kgCv33oC+JktK/+8QtY211q3e/MQyrjWk1Q6GFlvplOqVUpyhYrW71phsv9wTmdejVZTsGJs8AOYud4Fd4ntcePhIKoS+2IB36Im8ybKXcr6kOEonisCBH7oiIFKVKFK7hzdvyk/PvaCH+SIHHhhQl4p3LfyxL81h8ybeoBAOG8h9bsg+EzlNqxYkhEWp7oLXeV1LshWKrYsqg0YvEV3ytJaGbEg5V06Y9vYTicRFlYOqkMngZbG+BAZCHn3UeKWVTibuPDLnrp0Qn5WxFl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: tessera-turn
      namespace: tessera
    type: Opaque
