apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: banderillo
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: "@every 72h"
  name: banderillo
  namespace: agonbar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banderillo
  template:
    metadata:
      labels:
        app: banderillo
    spec:
      containers:
        - image: ghcr.io/agonbar/banderillo:latest
          name: banderillo
          ports:
            - containerPort: 3000
              name: banderillo
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      nodeSelector:
        kubernetes.io/arch: amd64
        svccontroller.k3s.cattle.io/lbpool: lamg
      imagePullSecrets:
        - name: ghcr-pull

---
kind: Service
apiVersion: v1
metadata:
  name: banderillo
  namespace: agonbar
spec:
  type: NodePort

  selector:
    app: banderillo

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: banderillo


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banderillo-https
  namespace: agonbar
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: banderillo.${BASE_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: banderillo
                port:
                  number: 3000
  tls:
    - secretName: banderillo.${BASE_DOMAIN}
      hosts:
        - banderillo.${BASE_DOMAIN}