apiVersion: v1
kind: Namespace
metadata:
    name: agonbar

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: agonbar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - image: gitea/gitea:1.13
          name: gitea
          env:
            - name: USER_UID
              value: '1000'
            - name: USER_GID
              value: '1000'
          ports:
            - containerPort: 3000
              name: gitea
              protocol: TCP
          volumeMounts:
            - name: gitea
              mountPath: /data
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
      volumes:
      - name: gitea
        hostPath:
          path: /docker/gitea
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: "ovh02"
      imagePullSecrets:
        - name: dockerhub-secret

---
kind: Service
apiVersion: v1
metadata:
  name: gitea
  namespace: agonbar
spec:
  type: NodePort

  selector:
    app: gitea

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: gitea


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: agonbar
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gitea.adriangonzalezbarbosa.eu`)
      services:
        - name: gitea
          port: 3000
  tls:
      secretName: gitea.adriangonzalezbarbosa.eu

# letsencrypt-cert.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea.adriangonzalezbarbosa.eu
  namespace: agonbar
spec:
  dnsNames:
    - gitea.adriangonzalezbarbosa.eu
  secretName: gitea.adriangonzalezbarbosa.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer