apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: agonbar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - image: minio/minio:RELEASE.2022-10-24T18-35-07Z
          name: minio
          command: ["minio"]
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: agonbar
                  key: minioRootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agonbar
                  key: minioRootPassword
            - name: MINIO_DOMAIN
              value: 'https://minio.adriangonzalezbarbosa.eu'
            - name: MINIO_BROWSER_REDIRECT_URL
              value: 'https://minioconsole.adriangonzalezbarbosa.eu'  
          ports:
            - containerPort: 9000
              name: minio
              protocol: TCP
            - containerPort: 9001
              name: minioconsole
              protocol: TCP    
          volumeMounts:
            - name: minio
              mountPath: /data
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
      volumes:
      - name: minio
        hostPath:
          path: /docker/minio
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: "ovh02"
      imagePullSecrets:
        - name: dockerhub-secret

---
kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: agonbar
spec:
  type: NodePort

  selector:
    app: minio

  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: minio
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: minioconsole   


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: agonbar
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio.adriangonzalezbarbosa.eu`)
      services:
        - name: minio 
          port: 9000
  tls:
    secretName: minio.adriangonzalezbarbosa.eu

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minioconsole
  namespace: agonbar
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minioconsole.adriangonzalezbarbosa.eu`)
      services:
        - name: minio
          port: 9001
  tls:
    secretName: minioconsole.adriangonzalezbarbosa.eu


# letsencrypt-cert.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio.adriangonzalezbarbosa.eu
  namespace: agonbar
spec:
  dnsNames:
    - minio.adriangonzalezbarbosa.eu
  secretName: minio.adriangonzalezbarbosa.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minioconsole.adriangonzalezbarbosa.eu
  namespace: agonbar
spec:
  dnsNames:
    - minioconsole.adriangonzalezbarbosa.eu
  secretName: minioconsole.adriangonzalezbarbosa.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer