#https://github.com/gravitl/netmaker/blob/master/docker/mosquitto.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: netmaker-mq-configmap
  namespace: netmaker
data:
  mosquitto.conf: |
    per_listener_settings true

    listener 8883
    allow_anonymous false
    require_certificate true
    use_identity_as_username true
    cafile /mosquitto/certs/root.pem
    certfile /mosquitto/certs/server.pem
    keyfile /mosquitto/certs/server.key

    listener 1883
    allow_anonymous true
