---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-nfs-ssd-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgCF/CgIX7d2c7M2XAtsd0Yvl/YwhUFoKqI4PwagnI7kYofIQjaS09JlviU5O9GJbFEKUNuX+jSBPtv0ibZOLmDuDUul2xeAbMVvF4K01oH2m/sPMBNl4gM1QyOe5hVR8AeMRPF0i50oPvvl+r8XhHjkGvjRWg+y3LnYxa5+b911xwUuha9db/WikO9H/AH85n6HykoT7TToJQkHQMEhW8azsriBLSXoaDX7WLFHvAXhNtoj7nVzbZ4lAPEuMydZXqssACaz09PlNtG+U5DZjjmMAJLJW3mPNWdoERt1WYOyHc3QW/23oU4ZEhaAh36rfITlDXKMkdPOCfuWo0gLi72jRuRvlCYwSABnlr1ZFGhL4pyENknocuAMaMWqdhplnrW+GGfecTH+TXo4aWERRulve7as+jQBWihFp3Oe5NzlQ0T+uaWGfEuhQRoT+i62uGYxMMcAqVOfNrnhNm4w0IhMVILj9aDrHxE2BpjKl/LqSh/7h0Wyw5HwxRHMm3efuIFJyEWONrfutgF9Yv6imhFVCTiFETIXoyzPOtqzXXvXkg2rCivCfIe47v0kt1GUUQ+xLhSFJPV5nNVn/nTGG4oWya+58KPgoyrK7Kt1Qw5BSNlJBYHOYCjpyue2sRCB7sh37fMUroJ4ATQ4zs/e5a2DWhJvvZJnww0i3TK87HvGOiHf6u5/XA3SUmcXQC1f+ae9Cc9d8F2ntET1gCpX83u25HwhGn2epWP7UCPLY1yhbxeTQCkfBfGyBQF6TRgcEyy8aNEWMToJ+1+NIJxjXTlXTBM2spv7ea76QEWeNvrp2pJdA7AQNrLPhWZoBrqaVMoqEvVsgXM2YGEhh+zQuSE7urha8H8aTenO3UYjaR8+V/D1eZBsOZqPmeM18+Eo6Kh1Di2XdGwKKipyy/D0OSdMywoHyvRfFeK+ifH16FRmIYjBLHlBQOQOss+L06Vb9LuXUPWvX5vohjoGWEGGQHXLkkwuiXytAPVldsUnE8j0Zt1VmiD77BkENz7JgFWh1o8WFo7etw85icg5XIYiUBqj0TcvXsQ0mluu0bEk2RJ3JvwtOozhgLeBt5hRAtNHF5zOtqsOZ9K92kbfmZK0Z+bR6kdN4ilVXB/CXsQc7Hv6kCIbGong1JRN7elacWnHnblj9KamfBlkyLQ3M5/CcLjthVDNrLUGJqOLuINfqWo1wMyhC3c9D3XxlWArj0eYNjF/ImTeRA/YiSOWMONj0ulUyjh8jTGFRB8Qu4wZ1i4YSQctezXG8MwgEMhz0d6gMd1iu+YR0GFwDYk8R72ita7NvjV/lC0221Loy2ftj+SJxdmQAbs959yifETNTIMhn81o8ytqTfHTGAeBcYY8kLHTskFO3+0wFJfQnHfynPy8ZftozsJJSp+WLi+W2p5Ea3cDaUletSzSaIXkSrzuJIW65N1Ms1p/sBrzI7CVfaMLHV3ruNxIOMxTNJZC3XiE618v/nAGu7a29njrfh13t2qdYwZKFYO0UPE3g/ULJj8s/sd+OYvryuVKIzZ3gTSo+z/mXPyJrXizj1xuAC0lTGwgVVf3+cTK8Xwx7g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-nfs-ssd-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-nfs-raid-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgB1nOIh83xP9VqnB9DnV2+pDfyr92lxce5u7HRo6qlnwh6NyIBijeycZsKdR1MPKZvmfqB9QM+T2plMm8zh/j7pDfRWZYvvdmt6r+mONQUadgn6/bjeLg9qoT1rkJ50gwYJQVF7BejJ+IjUtr4sOSQdElqrJgepdZ0vy/yPEgzUXHTQLwzwjvCdEzUS2nNrBGl4yT5IseZJYCrgQbvniWMyH8UaMvZgmzGlrnCwhu6cMW4i7RudbfaDqW534UAXG2wsSlxwTpxwO7tSc9x0FjNoOORtdkAnMzNvFXCY54EG9ovxcB+QSSsMjsMQsKbDr9Pa5qgU8OvwnUobbqz8aQ1eQp8E4I8wEcCeza7kSZww8udz/NwxwiTJS1JWaZJUcuKWfgM429raGurJv49zD/d6e3/iOJ9fs1TdfpjWTdPYQxZSAKwZ08xmtSWrqKcB/N3xv+jq71xAnU3aOyFupxUzqTrnQvGLhiHRJCuzx4x8gRcZ2QtyAUQFHXpXnKFHl3EC3Qt2Gty4rFIUUZ4rCGj2ywwuRehh886Xqglp7Ftsl76Xx/KzQdITL1IOXrRrraugnLZDmsJsWEz4Hv4d6ZDoJMiyQay/ghtKsPANUTeN+9aB/ypE7ZLBSBimLi/Vgs+NkL9rX4XCbNtdow304qhIJLFBkjvgM5T2k6tEIMX2Vbck++OHG/FC/9HPIYYXvH/lUour1JZF6ndwsPnDuRYLssfzvtwf+NmZRYVbfdCRuZF7AomWTKEoKS0wWMvGYmsExymBh/UqnqAecjM38AwrcT5X4Uq7rRf4NRX0EKwnjXozy5Of5v2B4z18NpDSlClWCbydbTqpFxANiZiCvyA96ygBdyDsVbShS0Q6GfdZP/J8/JRLvurKOZvWT5YyRMt8EgGudPDB/KtN1VXKM69zM4vZ/2tJmV1x5P2ACJHeLRlAkYf8+hP/nAYV0yaPXsMq1/R7s5iDpoE6jgGITTZNvt2JzCOifzlEmD9QtC6iKa5wKTjkiP7bZkqBFUbxHjLg8c4JITc+gWnxs/naBBx4Q5QUUntf7/4hHeOpSx3gLg3wFRhE34nX/H7LcZy7McQTy3XVIZLRCAFmb9tC/Ev0POla586ne6y33HvoPNw5fxMKjO8EKG/56xm8vIgAHx8SvozL/RY+s4fXCPHd27D40r5t0WsuMwO+yeNuEej/MSiLj/4+dfCA1GQmMJ3F02ShRHu6UsDwl2P7fD/oz9zHrrp+sWywnWMv45iM3oTw/nk+6ymjjuph8umAcnP86Tuizerq494nFEULOIZ7MuR9xFEMhVtbLvCskjD4qUQ05+F792FCYgK9JnPW+w4RUmOVihZutQtn0juUfJKeFcE+mF2dxtOENJR4MTP9etkVCG/ZGSAlqY8LgK2CL3QS6NFjDy867pEsJgW5ZF7A8AiZy1gN1BJuLqVxJQHD4UCIwMU8G0/yvHtDhie7ENfkK0gWEBFpyT3t290d2+Gpn7BKYyXqgYlRt7E3POrkvwlcY7TYY4mygR7ObrS/Q7yfDaWLRwKRHhbPaI91naUwXEQ2JfVi7w00iViE5Ny9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-nfs-raid-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-iscsi-ssd-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgBulpgMAMqpvW8tmIELH3+RsCGTJHjr5btOaskbaW/Sdbq5L67Zap1bzzsq2uDwOZmyYao0C9CY44KyQk7Z+L3WfrGQuj3r27Rwc78cBTJ/sKVt5icYI/Tf78sZGP4e0uwynybW/RKD+lUPG+n+etFvrLQyLaqZjouhL6kpt5WupA/ylvmlmtoKIFRuvK6tF0x7SAwUxp7h8MLLNNCB89Mw6+b487qNfJs61fS/x+AG3oaEkOmNZKJaMFP80vUdYOYFmBeXJgrdMsaGAGWT4aS51FVz0rjnvjHLsdSINuP65unE5sC2RVY6NLrz1mGmx/z15JnXjZ/rj52Pnr/G7QlpTSz+KhtzS6byTHkhm4w4VNKxd6MNpMmSGD1NcU4VrvO7KUzOYNLdcD3g+oOr9SMuzfmtwgpjzM8l7ct+Wn9i+45YXzguElZpSYmeGJrV9vAAasJj5Heqrzr9r3fsFUsVxGAogiNb5ATPYCmONGiMS3SCRyONPubYyXYKNs0JazuefK0R4XZ46ecR8QW557J6GrANXj+EYsOqJB8eWs1sXMB6HZMctlvWejaDf3xypCmyffS5Xr5j6Euu+2fEZn9y3EEGZun8g8rmtSC0GGJhjSoSgcjB1uewsc2QWXn8L9qUTBodQzVDueM0jLgxBM6T/aIyHxbmd8gLSGH6lp8jLiBw+WUXSnxmbX2oNyu6TRODdYsmYjfbx7afSxz9rUJqG0HVu9X/5zAeMv+xkKIHgRXMiS/ReN8AgYesWmvxy2B8+vBAwdc85iPRmP2bih82Xj2cjdTcM0xT9kWf8SS015P/LakoW6egm3dKT8w8WCfLpbrFV0RioW/7Y4AYxhNVuhMMtyaHl/9aOajFLKV6SPdXMHw6J+M3Hm2dYonOXxG0K6iM7lJ1f6DWJygWq7cFiZJXajOnM3lWHfZohkiQdO9t/Bke068QLiJIeuUqe0ntqm4ANIIBHI/dxypCcQxcDOtVDPbkVQr5glg6esvO7ECW+DuPINsE38p2wAnZSRbcZMM36CkErHzmL9cNFsgmxPeYSAJAAkAGpi0gsZFBDXPtAWh5r58sh7/wy4Ek8EVF7nwmeLxsoa1xLGJ9dsBIT7yonqMadjLOvo250E8W3VxIJTlcl9Ij9h3L8NbC9GNYEdTs1do7oqzajYUYBke5K1xaMfyCef/BpxXrLVB8OihJzzTEjHjyGMQhef6wB6+sqGCtzy7b135oRPwLbYD+mHdoju+fjqyo5JltOfsCNutinUoT9kfZITOXoQINOFA1Zl+rzIqNSVBHfvoO5YxdQDYaNSyzpGc81motE0hg6dHltvtwOXMiD7/UqYG2ua+mrjPhVYRyfYPAouJl4bj1fD4xf9C9C9mdHMXkDogmQcyefn0uLtlNHSMp1XnrYjafVxzELOsSnmRUFVFWIwkti3HY4mM4syYV/sxkaqDcd6eVksH2lJ5mJiRSV9UpyrgKh0ma66ULlUNT8P1JXnHWgSY12vVGn5tv64P4eeW4zDXei6teQW3tzCzdmdSVWJnG2fWBpLt7Ax2C/pWvKfkKZVFYA6eHveH+Z39qHap2bPcH4ntnx/gs1WDSKWborBujIOi+n0njh0VfwO5HRp9d/AQWlFmHjUTTq96PB/7Fa5qjtfSDj6F/KilQJHGUFibHRyHw2RJywR+JWIh2V/hae86fKuhyNhsoshhRB64ecM49t9F8r4xLuhEqwcp1f0Ar3bM8a0k3wNjsopJU31eOz1jR18r5/UNZsvkWVDS1Rpq5BnEi3tw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-iscsi-ssd-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-iscsi-raid-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgCgX3s7GG4X4hf827/a7HYYGTJMr//PDK3sfceYcCWsDI1kR07R1YqR+57ZXlj5kmR25fdVAS+QJieie+zB4+iyoHBSCzZsO0IKCWTeFAAKn/V89ngihqIWVpFf8V1we+P39WvSAouEl20oD1V3lguU/o0nxK5sHCAK8CQ8FPNh4kp5zaG0uXlR1882gfJWWuOJ7zVne2z547oNhgfkMor1TqUR3/7fVFXYbTQYU2BpYlxsizOsZAPscGuyPOkv5GO06cYmw/II7iDrSQ0d/PCKJkVv3s4RLLbuWuzNdPfs6S6Q/+gZZRvl6vlW2xoGU3M6w1gOG8trNTSpJlWz4rQfIyDSO2w3fRbGYZtWF9Awv0NIuNA6hRs8O/ZnXuWT6vmGVMAWyOhonjvtO563vIZCujPuMJ1SqetlBdA7thzu8hWFdn7evMUBx3AB84HF0jgFhKcp0AcK5zmpaO9waGpj7vZ1EKDZ2K278rgfvLsCWL41hyj3Q1dHqeRSrbfDw+puWWH+B6mvd2qI/2+ks0vfoRnZvYAiuPgEdcvJrbT1cJH/ov/WGQKScVMFzRWpugDh7PcOdkp+ejEhmecIhLxWyI03cNfcalQRzLUsfpDLMKp2ye7iyuj6Yo4RR8JftvGd5RWtierV9xF/20U92f9XrCdlcRM682Qbc+EcctnnMnIX+zsat0bs1L8+2zWFdF/wLpeeM0mpQ64V4ZxZcGQt2FiGQCG1g+40J97FTkKUVgSAc9Bp2l5f1wi6y/avkiih2a+FeY225EDYGnjL9N8PmnCcdBs5bmKnCobjv47frSV0b/YwGIqm56Rl5wHFQWiSsVQM3bQpILWBgLz1+J+8qT6Ro9MGbwPG4lPhcAfYsgUtfV0bKWC3e7CuKzTWq79E5EsvZib2mO5H+98s2FbcujE+eWsmJXQyfB2t3pd/O6bXAZkX68JEWIETNbDTqAB0L7so10CQmafmbKMmYYyeOoCV7/8XxoOH9YzOJW/KhJTWYdy6Rl52YSkS1WdKh2+raTJtJEDSQL/qqgRsXE77Cke+St5p3dyK16s9Lkeu5tQ8y7sRcIzVaMHzRDzo7bfGeCsF+i/3ypeTPFYLTVv7LKAlVmICsJ7+3+hBl8tpp/UPZQyjQ/xjr+BFn9O26MQC6ur5yE5eAbn32OZED75S9ZpXYgmmX1PD2dQMAM9Hj6G6+5bHr6yLCoLmjybiUFTNZLOA4HUT06kz7HpySmV8VpkSIPMoEdE19v0ZIDP6MhZkcQA+kpc/EJ7iq4iQi/YDzZGO+yx/2LqHtSMp3fzmPNOshgsnKHcuK0FV1WkyAnIBzYSIccSDuw3mw52ZxLj94+yCb8MZRnKi+4mdBdff6XQNoDN8f/nYv83Ea1I/jdIM6oUlFsKXX683iVcpL4z2Rb8ol20inv7+Y7/id3EQJL2/GglRqO04Xv/51YXI9svfMC2nZP2LFC7xokXgNHS3jZcbBzJ4FE6bZ8N6usGr7QaI2UnC3iLZ+Gk6VmXcXNtwwzhx5ho36Z4dWbGg8jpJaY6NH3v/h3UuFMR//+R3AwRarn1G49mOhPB5yH9pd531CpO5LJ4t5T4yt8VOpM21LxfGQbx0BPQ+6wM6XHbvzeHN1iGW4bMxN928NUj3DrNhqdU2SCMi1YD+05RV+P6qYzZsakwILc6c6tLZS60qkdffmpl+RlVUrAczKxyrveHXGVzumQBzRXMiBicTFiOkTB2LwSGLBqcohgtPvA7aoipkYDOlim3a3BUPdqCQErZ8JK/pQb93e74=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-iscsi-raid-driver-config
      namespace: democratic-csi
    type: Opaque
