---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-nfs-ssd-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgAc3PddRf+xPhUA+dVXNC4uVqLyTFPxQLqkpS5ogJGj3uE76jSj5cCCtEznpxn6Eila3IwicTBuKMbebXE8uhqTw48+YNsaotGc0QyJoUO0NBp6k0DXvHoS5rATQ90OjG7MgMrwhrM8rjnCHYuYZ7JzhzrI6h44uFhqcjwsaMVzGlLRYkCRJlBbNcv+q+i48bKrEPMHTT1luB9maUFtd7Wt3CbKrm++kduVI/XPaiaVsG+r/eSJDezVvvaeQarmMWrhF0Sd0VexGE7XplpVWflA15xFzYw+J/q/FafNrzXtOvzTzo8tm+dQ6+P/JYQqbCYDUX5RPyxRmxZTPfxNgO8Dqrg6iYg9STGY1PRXwQjsuBG6KH2bGf/7k/q8orLrEL+CV8oaIsdovsECVTG1UKRrFex5Z/PAoh/fA3yHkGh+NWuAS5BfaSW4TWUOxDjCJ+RUoBYidJtwRv8ULqMZm0/699U7gJGA5lhI4q5i+PC3oP2ggv4oP7kbhxMF9hNzNaCRn63jLOKd5geQkBJ7fHfe3zs5PzcVWRkIft/l/7qkwG6UJGNepvuq2KlE5wGeyGGgl316JUNKy82q3M/DGQGQM4A7xviwc5jnPDpIVtoua/CfG6qxPU0vfAUx58d3akN4p5qMihLkXIHg4GdvD93PmsKLfylnyk72FQbMN5XEyS86y/XWW/8AlPGioGVWVK3pcYNUPeHi5h66KLjsInGaEy1dEM0hlgtAmgXQXOlFG02zYvuEAjA62qACQx8PfoqCW4ux5Nx5Yw8fkOo2Gzg/VENBRNI8j6EEavZeLDAg0cudMPS4cBiJw2kWiu75kToi/9BwT1BARJxr2soBt9zsLmJoE9FfzKhJtrqUsovHqesLKlWrUJUH7uCqLabHB7x6YiVFP1fG7WbqiKarciisg/Rt93DlhjXBuxI4JcM/gx+PQ1THI8izDH/24iavSSZ39xfHe6zMUjX+fglPShl6lrkScDq9Fs8RiB0rnflJeyF0XYw/mOTEICCv2wOOeGczfveE20kHp8Oa/V3Pb04jrDzuvJDZhEZfZWV5Rc8hD14JkEVVRGLzpJEqgitbNh+vexrYuX1X+IbdP7YJFugALjTJCoi1Wgr3tWqWdHOhK70P43qaz0lvNB6IoHlOv1B9yL9y8iyHPwRJjufMpWyAxva705l1hwKepmbwhekojD5WuxfFsugwI2oMhDxSiikhennC+/KqteppTSS3aD1vl7YcY6c9Bo4M2ns/zT26lparpvtveogc7DeR0BTpxPH1hteYemslf3A3spKQXy6W7zXbUZh8vxVC3emP3rZfG+DH0DbLyT3aMzFDZbnliVf/23V/gI5h6WmY79j1TATObATraizl0uy6ZJLUFp5+RmdRfVjsUCKt6YLn/gB2mmPMAZg56IGmlpFQfneowfbTwnbN8MWt7O4VPzcViLGpVcmlonySOqiLvt29Sn3UIKp3Oa8BsEz3jASFDLzwDtkRHvYNLsq1rNsIu84w/sPAdc1rryMihHkkLoH9YfO0u2zC1jKGaYI4LSJdFtN0FvsUaVfyeeAVv8ivGg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-nfs-ssd-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-nfs-raid-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgAmMnwmeU+ZL3D3exo8fMMPI7I64fhhZ0ksRZjip6ezkVDub5Hp9HFZlottHd4GbGTdpnD7Tqh+7aVDTsdOjcEPv/krhxFUXhzc8X5wsY/Qk8T43UYw3aUAgbwnWftSA/n8mwzRx5/vwwjnt1fnTGFRSangLm5xaQ75MiiUS4qzOGVqvKAS1gM9UTOFM1niceDplhuWhtuZAGaBLaKvbGy8QEFwV6AoW9fd7LdwM5zwAa6qWDtpS8aEMtyy4qkVKcwf68R/dMK/3yjIx2cTdx4bWTekqzAwTCq/nvq3HwaMJxae7ERtsgq98QXPo7R3eW3dc22gSMlJkV2QxF2k6T5TFHFsImFRz+Spq5udV99g0kX8QqbVXggzGf1dzKMqv4rmGLBiHunAmJaN2Pj0XJMiJVPhN4Akz/SA7N48DDS54Lj8uMbR70I0v+rn/9fkZG2fJg0AzKw9j5CUm+Tm21s09/TFG9esdiyu5B7yj2TvSPUzoIfLQ/cE88w2RTCKTnncJO7YTpZsBGO1AC3CLDKlzRhCLJgP8QY6rGBfPpH+WSvrcpkETN2La7GKdCBhuPueJ/Kp/+SSEWq8Sbhp0iqS1Gt4uKkP0HYjlOFOxcLbAIq2m0Z0ezIIaMeeud2Z4zobi1ntQYHUKUPeKW7YGDOpvIFizhEXMRSvwEJsYKELuaWR975Eh//UAgrTj1OswR6yKJPINSWsj6sUFIgnpE8aZjYT/N6yzKS67hVwtBROIDQjSMdwnxCkHLONvrrlINP1S8XorlNxdgLU2js4S88deQknzRQUbeJyadMNOh//V1mSj5FrA1LLDvQvDD1yibSGE/5mQFpDD+A32e/SUbHqL5mOBV7AkpEDj9mG5nQZPRMKGDRZRjFS00FKmnW7zLvAteRNIUU8+0FWOIdarhR3633J1tisXnDtoLXQHpw90PP7X7wYPMAgTp26/a9buh88GAu+O+ok7FPXnFMviJWBaw2g4UdZCwJV4J+r9K9zwQLTqIbiVShgP3WzbPL1DqaoQYPcq+TJg4EXFTBnf1DQK1iJlv7dBO7VRcG15yFN4vSR0o28Q/53sEazMNaroa0IN4klz9bD8vLfdMgGoX04r+NEWlmkOOIfx9QX49AyU/y9NIrtPH/NyGAFzhoI2f9olffCuxizy3C3mWZn8u3abLysRWUSwJfAk7XCXlJgctwb9fIT6VAvIe2gkrGeleHia7idfqbNHyG2wDiMRykEPBACbenan3mS9wZwuboGdvXGm2qkQAJKwPcqRBjUdB4PsKqW6SJIGm4YA3czJaX3u9IXWMTb1g2kMVgnDFq95p9F2xLgOeYaX8CKl/hWgji9n0PxIBMm2GWgJEB6/vxBmGxUS6WzHtr8hrlT6iI0CvGC7XB2KvYYBjYWKMo1IiO8SvbN3x4z39xd/f+10iAWOl4tds296m/LinqXdRX3fDuQC8cf5+EDL7Lz/o6U1QJoz291HqlXgbpgjykJkEVzoGSuJa/DfKzLVFxSZc79Yx82F/KM4ISSK67jeKPWvK9RaPbPS90ZV6i71Ka3zsj8DWGhq57zeZ5/Yxv1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-nfs-raid-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-iscsi-ssd-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgCaGZI0JVA7EExgoBXTcyaV+/Ht4ID5oW/j06a9/9GNrY0f1zFUZFmju64zHGJuluO3xcfZMzdG8TfRsP/SKzefG+NO3Awxas6uUhMLXtxBojQ1yevWLPyX23E7IaRpE6Joh2xTFRLMGtkUHq1dh0s+NAbx8i3I8b7QxNwhVETE2RYmydYAJDPOqqjh4Gonf+dueB9air4BJIL5qPxk7PaTtAHEbnzsp1UqI69mNLaPE0PF/A+pDPIiX8ZnSeiMRV6Vh52dB4oIU0Mpbb+EmBJu4Selp0jCevpMjZaHyRHopLHMn4oldIp+RKZTkcc9Sd5SuGUe7Ji4GjOoKVau9Y4mklvkpbwrrLSRYhcKV8baF8NU+TBzJmQ9ebBZCBtdFQR+s9GlzvbJKdKqh1OkCfjbk8XGLr0FwXNF1Ag+jn2QubOhUkNeIMBRTzJ+MEfXvFKAF1uQvHXImAEENEsfKbHIFivjERyDbtSMx/ByMcqvURF59B2UQOG4MNp2qqXMp0/r2AIqn0tGXGpOX8YpuDhrMgnAAyTh+3hV0SbIVOqZ9JErYX+OMHu3jVEls2Jk3/29dfE3ayyerke7h/mRxON+qeC2AB/aEUJ9AWIQg1LgkOfwDdwpg2l/IRCdsisgI5aRzXwLipxNzQx7RNMXk/IxzTSy0969pjA+/rdH6ca4e8AQ1F2Rfd6cVj/1kPBe554EdQjEnk/7SKS4f7ZHCvOq8PbR5Qbx+ME1ND724/vPftdb3rChMSLq+U4UtZFDgsZyPasLy50OqurjG61+OX2WJQm1hldzz5YtDJB+qOh9TQfWrAk9mVtGVJrX/CRr4YRXLTHDbaBb/T+3goWQv76o8zbaAC3I4R+Zd0dE+/K9vD1GWM7fHd7FfI4dBUH/LHCPNEraatnXdm55c9kbSd2cyLzGuhUGMNvUOiQZptYdl2uHd3XTXL2vH6SJcztqNeAxAZTy8JXH/qrB+l38BhhYpwh/QDpJ3jAkYTs3GKhpX4E2F2nXxXHChwYtRPs9hx0AuRibh0jwZCrgU8/M+W5ZHEHjAvmARPn694w1M6JvKD1LPmu0y2c5XfVyXVNUypsKtQMyyEfplCe6PAQXe+M/7APp4VDs/c1AvlbV97HJ+qiHee9n0iuEHvz8MhJ3+e0xYvuQa0MH99W7Rl83aBhmcxhGtoNH+Xkmh9mQNoYMy2NEnNswHuwdTM/sBI09hkTYUn8LToaFQVVXZ8Nskq9H3Ml+gw+/OpgZcmbKanhvn05VJe3xDJ+qkkYNPWzJRBMfF1An0sEio1WUFj9v9y8hbVxvw3vEpYNO/mRSrufIDqMCN+WcVTNgQ6wox9QCUuwoemg+2kNA6NgVL94dy6gL2jCZu0AnUuVXfRB/E6m49HD7r2F7uWmAFaUykHLcYtwjrC9J95VR0DHjzfp7syKKiDg9xGUbCul6DfbVM8iblWMMx+9UZNlQC6pIQzORPM1XRMQLqmacnsOhsV7KWX3cWZhXJ4wU4u8leHoopddB2CckSTAn/hs9Ussmn8U2I2q2ddDPAo5ztpEJZeMEYaaMj1oX1JVnjX38Gg4PkwQbEvnq+XyxaQ+Xpm87Wz4VHAxVCXdF+P71ehiZqz/mzJkUTuMN3b9JM3JTqdvgRN5vW664Nrt1AXKf9ykYllPCnwV9Xd1RgG/xHF8e1vlVLuXI2LjmuAUWk6ikMca1Y3DuSD+SOkw1bHY/GSXWpg2E695/DgT+DfmuMIpILiBf4/rTLPSpejBCWvdkgfm/8RXQjx29EVgfLrc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-iscsi-ssd-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-iscsi-raid-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgAUMiGnExiMM3fHN3bNC3EaU15Z9BUNjTkSV82HiSwJ72r1IU5fmZO5ecI59XEcjiSUxL+v8FEF7ku69UKNDMeaxirPeRVrD6ObHIdsiOpaas4W+g1NI0vqbGoI6eSyQU02YPR1X12bhsbMH49zpX4xBRL5cEeERCfWXpKmWhfFAoaXpjttH6XPX1nrqjlyTuMLNqVeKqSEvAUGRrAHGsAVBquIGIPoIsRH9cNI6OEgx8DlkUeuqlv9shEmw37S/XPhRUoaOvF9QXLlfpOI977lVrATpxkuGwh1BeepGtCu7iHaaC4l/pkKqHJNoTctjit40xvOEsPU80XChx69lzPlxIDMtyUgjI6e6tpk5pJ/8gpAEBnxxrZc1Nr/1jj9d7hkjtC0HE1ZfBPtqjVaJVGH1dasLK9c1fh1YtZOSeHce15jOfC7aSq/f+UoUqZd0h1T8KtkE5l1PQE0UCptx6je2RYppOS72cIs//W+nJP0x/6Ljymc2lFKNgsmOOvE5d8wUKsrRJiK2LHPbEAiNv4j/slps1IbFtiLMpIgzESY5Q82qsoEtZCHYu5fau8a7O3SWSka5J3Ku3M64lyAK9r973mlBHPjkOSIFAuXT+oWRJgYRrXlUSZCLi8PpqEc8ColzlX7Qt+X89BJsCgEpD+hYIRwJN9udjnV8gNLXCyUfaceYpUb4omrxHHbpBKiN2gM0IPsEbJKMCdXO7QhebKbkY7zzLUlTMUW+PQJa3kFWC2uoUo+ZszACs99gq6YFmSfoeQ0GZ60JolDvomkrhjnwFXSH7A742cLzmZh0Eh+d4syh1R1SBfrIUfHIqceaXWYOK3SYh/221b7nurkvXlG6QV94FrIv+W3kdpl3IlobsztCEBZb1+t+GTNPenrg7d+2ojSmRIgE39AZxBMBIjl5ragWfzRkFb5AlMSfW1ZzMX1oHOw5twl+z1BFRk1tXK6a+I0PTfm9DqvIEZ8MR1I4xQj94I0eNKXpxGTAqPQ5m/6aEut9ySZq7/EfbD5n4jSHSeZtp2+uYqgPz+it1VZeVtZSI7Ru5PjEITsRx32x98OlfNBvCvSDKKPqTqMy/IH9N18TeM5fzc6dUeBmoOLNVzc9DI8sYcbhRMdhTW3Eq+NWx1nbD3fDGXTe98SMpSgG+JMDcEVxK/GgexmuUP4oMwzs19MuhYyzY2bx/sij75P9dDo709R4w6tXjmH5+ha7BDurhX+RclLnh6ydgkUKuJF/SQrJ8xkWwRwZsrL5f7J67hQuzLm2XKUy0Z0yZwU8t4Hlt4D8gk94+kS5UA5cH56fSU92WQLjd1ElWt857lKjtG4I67CxxgfukLeYZRcFfpdfo37TEVmyCnH6rEBPVYmxGS4AvcbzXeHNcmxU48XyWaum3hcUeD7zI+eIp7+2KUE7j5ZE8PWKXd+LcP5oTA/vEXRqc9nuIltH1xwLBMXl2jmOTa66waq+HavA0D9ZnlHh1/l3zBWmOuJ8Jaa1p5n9kQ5dVMNQrnTcgrJwE7kyocXPd7TOB2ryE8Cfpyyh7CNOl90tAiVcJ9CsNildqiT8TZtWMjdf6i3Tez2Yy8E+xpn3lXMrxzKfAdyi18jxqXvG5pot291IfkEiydcHojV85AK/k/DBogRX+2Vj00UoSmDgiduuEjhJWVBJB/hAULXaXGlGwxUqM1YiKOIOKjvh/OQseV3j8q89qvScvHmkFJycAOvaxhU3X7AQlBJMIKLdNgDeTm6hMbhiknNS9sA99nNlTIRunOq0RD+v77lVyWEHR7KBQ8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-iscsi-raid-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-iscsi-ssd-lan-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgBESYZgHlpTednghcCODDhUPmcOV4hOan9QGPjaErvSFKUUTOdXuiptQ7gR/io3KIc/vvDbuO+HZNm4fVencrcYabaF1Bljf6sggAjC0BwXB+VZpPKmphVOpcLOuqFrIzAhCDn9pBJrrZigo9mCF5e8L5Kp+EKNvgKTbHAxbvhAUWeyEngNV8y0/sFlVw6ZXGU10xYhjb8EYuwoisM4C08S4amezI14Cd9KMiE2SVFCxDeihefKppsA3WNmiaXKIPmkzo6bvogrMkZcXxvZzYFnKPjheH629BVc0Oa4v8S77wvHB/e5angMEX4VQ+R5pL87sefWZmguNCFxr6eFZDbjlbQWKrsQjA2nSkPo/HLhHjk2DGPy7rgru2WI9KLdnX1r2IIm1lNzTGfORT3WYFU94azE5aoJ05LOtPQ6kLrRf1LhXcVudGOhC/T2atdNupTRBDQRF4EBhByHnoqtwbtGKejXVTOLr3h+cI/CpV9kSVV0xq+8oQ8Yfd/mTSi8d19UyosgBoyA6qSAYrxnL6OkuQBWys2gpIojkEr73Nr01gTxZt8RX3wyGKc/GO013BBcpiGjAnFA89265RQ0rIb7h+U/BMcgfQnNsNH90RaIzsVbRfukPhrJi2Nt2x/M6x1TgtGQm+yIiDN0kde81v3RNzes3hOGbXfiBeS75QTRP011J4zyGuLbcYIGN2Bi85sbYVQCyjRPd+hcEBIBDlKYcwZOe8Qt5xFOhdE0OAucarLhUHSeqPi14au3HPBLziB/bB2w9wOBWWGWBuuNff3WVE3jySNbj1ex9z98BjL4lNEOMRelSFJdVADyLakmna4/dYk/MVdXB0qPzyU0XsVkeS7/UFJKuOqK0MLEqmgeRdnejdEMLCLFwgD8PA4w8LkwR/E2N9p4dniOdb3gA3r+BK++nsCiHrE9grqGXdVN/FQk80dRH2ThGWXUcSgW4tFyyegV2KOHG6bJsKDEFExeZ0n50K2if4ey/XD3bClCqme6SYvB6Zj4qXrcW/binAPCXcYyjHw5oQNMOLL19TIybUc1e4Ygy5Ff5pcRfFySHoU7WygIL6PHXRko2FGOXJYY1Cl/j7IHpVJ26Tj4AWiylRYkuLuvAQSNGwhBkXH4WCdJt/83qq1fHov6fOMaP9U0B6chKbt0MI0gDmylULjtMRpiLuv0LVvsEwW2PY640IagTVoPBagbHm1B4kaD1S2PwSsxL9+fcUNohJsSiXtaJ+Z/Sn5aW8WT65EcYlKL7G8uT/MxCpNVv4uG1gphTuuxqjxJio+GbhhJs/n0RcblgPjJV4WGIazYu5aH0XPZ7rvE6PaTsjnea+Kh6CerzWF78d8+PNpvs2aWbHKtTQoNSyoUu2nA12a+yz22Y9aQZYhSHz9Om43+aDik7ovntozVcBJ+Q908SC9vCp+bAIqHxZ/xKVwmQ/lcqvrW3xTxHLxWHpLp3YRP7WMG5sCUSSpg58qKoRAzEs9vrC+1Tw2e93nCmYBTzkRFM4fjBC8iRB9OCHSkSZROJ7GE3Eb6ZRzvT77NzjKOlEi+AgO97+OgxpRiwgJstPsy9ztUVULNAdiLGxNbHhPy5iQeRPdkrXnnPDNI1ATgCqOQOqVxBxVXe/MCzWlVcM8I6mDb7XPsFlm531hLcpjuXtqdSHhHSwwhPyuHIW2kG8Fp0uOuCPARk/fxE0ZSfe2AfIk7HTaiUUlSht6nfPuxnGyfO2yg+hP5kbhgwkIpeGq3vxVGNGjj2uyIsNE9oyWZCvQNGtHKQV/XYRbo7hz6Zw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-iscsi-ssd-lan-driver-config
      namespace: democratic-csi
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: democratic-csi-nfs-ssd-lan-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgB8PG0kDmv5EcR0Qcmm+5TaYcxXEpl8cpR/fSh9fu++rPmVLNbIFTyDLGJT80BYAyusc13EVE4AHB3W20R8ZEE1I15myyJqKb4yuNjZ5WzvKRZgRY+vDBhjSd7bXe2NkvVTxRQ516AYcsIj8stq/+c3HuEa13C13rhEy1GL/mvd1M4V1h4mBOdanfSMxsVsYSYJxm36Hg9M8+1ee0sicS5hS5vONQ+E+5/yAUy6A7HtEKEmN4ZhIuZI8Nbxm3Az34iZw/loNl3Wjhs6btWXV+q3w8DTljVo43544F/V3O5ofZmkyVPjO6DBiBq6ttpxcHed7CAmeYJKSwy70h/HJ8+QVKEOahMrlda9nVdLceO4npBQYz4FWi03cgiviqRCMIqlAAdO5l1gZMPPEadMAWFkfICO7TnVzCzTmgCyrFqcKh2Tr6VeKMb8oVwKA3SIDJmQJRTd//lHpUpwJB43jTt1Nrn+YIiKfpp5wjOOe1ucXtwffi9Xz/chkhQ/ODll3NwI2zsu5Tw7vYXGohDgjVgI+EHfBeblAo4U4mUw4oIllNxKkHjhMuvo+sK6tjHmIV56mRXe85/2KLsIjaPtDldnoQK7xfAEop2MdNBUL9PTFUOUVvqc1b1vymAsTr3BLlAd++VnvJEoAk2rHBy19x8qWWs8JFmVpyKBX5uNcQAe2LXPVvi8Dwae7ZxRWbUP49oHOB9ikMgu4kFZvpoiaXwRWY5JX3JWCUvWtPQ7FeOaV6zRCHlUzH6vYesIAZpcvpcDZQ7R2EFp5pq8ob8+XyxNitdoWLYvYcIgkDpFGrKatYVA13OWrn8V6dWmbeFAiIhpUhiifiJPdsYU5NOdXmQ8fiqwIefTpbZSk4vYfDwqT1FpoVGl7RMYVUtRzhHySQZYafEZT000rc0HniZMf4facYHQv5beBPI2BZSIDYA16KRqoAm2TsroPC58OhBxjKbpj9FuWvu+8HhWTuN9gZL6Y77f8n71hTCk3eg3+cKlDI3r+2P1OydkBsjJKOVN51nd6XfrCNgrXoA/CNO1llWpAOMiC0PmYZMdh/aDIt873IL5jCvS3xGX6D4afcN0bMeW4ak53OuBIiJ3Wugi7ymCdzoT8YrYlyGT4C/kOUNAl1g4p5y7zy1+uWIWuwcxEw/I5HA5S0v1/lH1/kyogfWEUpT416e2Iye3pTteDV1pFFb50zN5mKMNzya1ggk2jPBQGwg3LiQxvviVhl5ECx0CpTjBRtpym8RslsuUSgYJvn6ROr2Kc5/EAJDrASBG/XZin3JqW6MeYTGZR3K2DeQTkqvu9yvKAtyaN78YsZyvapE2RupkfDoy58lqL8LvNEo6YBlIrQNVaZpq1GaPFkTkrfxrqVAdJ5jj9DSbdV7jsYFOxrLFvdG0kna33qOLLbfB3NlN6LYYkuGcn3iBdYBlZI+aoa832aBpesydamrjVejkokE40a6rvLGrg80KMaiLKt9WwlZh0LcPaQLu8MokwmEqSb8Copss/XAlzAdI3HMIr0xYx9ktP35VA+C1LExW1IDrZq7cM8gZ4KmG2tNHISR1GqMZfquU3cFp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: democratic-csi-nfs-ssd-lan-driver-config
      namespace: democratic-csi
    type: Opaque
