apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synapse
  name: synapse
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
        - image: matrixdotorg/synapse:latest
          name: synapse
          ports:
            - containerPort: 8008
              name: synapse
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
      volumes:
      - name: data
        hostPath:
          path: /docker/matrix/synapse
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: "ovh02"
      imagePullSecrets:
        - name: dockerhub-secret

---
kind: Service
apiVersion: v1
metadata:
  name: synapse
  namespace: matrix
spec:
  type: NodePort

  selector:
    app: synapse

  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
      name: synapse


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: synapse
  namespace: matrix
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`matrix.adriangonzalezbarbosa.eu`)
      services:
        - name: synapse
          port: 8008
  tls:
      secretName: matrix.adriangonzalezbarbosa.eu

# letsencrypt-cert.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix.adriangonzalezbarbosa.eu
  namespace: matrix
spec:
  dnsNames:
    - matrix.adriangonzalezbarbosa.eu
  secretName: matrix.adriangonzalezbarbosa.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer