---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: sure
  namespace: sure
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBOnJxVY7D2kldO5w3QAQqSL49jICl0reBHHAPCvL+L/0ZzHoRLQp7zfh45KEkVRtV9fXEXPFKVzMZHzltonksZF+Y0Z5yk8HyiKfo6glp4fIkhKpLPWZN41emftWwBUxDaC2mib1pxkNh5TVkNjkZoG6I+RkfCmiyL+TcFaVVi1k7IQFvB1VkatE2VdJhoAPyrG2bq0ABUIDEOyqrIBCnH9PTL8hkXbxAug3T+8PgXC0I3MjCyDYxmglIDedyD336F/PgWzRQA4HHDekjkSUua5aCd/VQZf2AXQZ2WUIhrLMfLQcomL5AiBBRqWvpgy9m5tTqc1ENxq4f8NrIOzaDic9ChCzekR2Dj4IEC8nSSGf3eSyqBx4AXdI0xGcR2iy/fkMBKLxRWQPiAUmcAbtPa9C40lbxX0+wkE3ZSqejpaW7cbfOUnn8+LqK7YopbFkp9Ox3QsSJTgKFiej6JSF8GExB46w2X8nuvVxe8/NPo1RvK4IRPFMiFNx/Yt6DlZfbGNJOEhRLo803FS3VDDAcxH0fR21s9ddcuAy4MOeJrVV6OrNxQtmQaeCuf+01KtoXIWq6oA3DXEsLQbNCnuUEzCo+MmjE+EnpFDi5rOrJMJ9VD2yR5JUVSVDexcr45eYYXvt+CJ9e3+qidKtmTgmdSlvatuZ7Qbgf9CTc7fjlPTndc12PpmVucG/fTILlIq+cV4++Qe3LQgsTZthV5aju1sXtxdp6e9e0IB3foWnMe2A==
    SECRET_KEY_BASE: AgAkMfH7gwuTIsV/9brxrwLTGWq7059ciAPzydE8RMBTK2KE+moQuxtOySPIrnZTu+ekjmyh8FIGFUxng9xh0RndBe6jP8KJMwothq5LAFtuPGlLyBdJdm//QdLZaH/lV8g88lvBBe5Y7iqWHW+3VIjTSqooi/j1Zpj/POk9+Fzt5bMObE8u29sbwMoXsnA3kgk5/jQ33dnFRh7LwX3n8p3mVGsuipRjyIxSep3BOzRdLMVpo1w2U2y1oCE/Q8N+tvSqHDOpx6l/ezAodavnXypCET0HUySv6+WwcFuGyvCnP93omEIKrX8O1A0ZhEnxp8kPbZdfpq0JYtxmyrX9YBUnbyfwO1yg4o6bA5AIHALkBALmjMZSxOqQ5wk0MYUhGzAiPl6nHyOZWRqeCgLLa2ULB+FEDGd6ONFx1EFykw9TtYrfza4yuf7H06G4B0WKULaiNikMAkAmzYZs8/o6CUtHetA0lhfMkBlFejLEGJyw5MR9h/8s0nNShxN3tigzYDWMGqxKJ31J3HgrklaEMVqhXll9CaxPhTGNtYdUJ1KoEOBPfTgLQMiGQ/Jr+7gbLFfodcz5tQrDdAkvgVoWm6yziPywocmZKO/wYHmw0JKQhcp4fOs9F52yZfXj+WRdNY3trpCyTiMUXC/0UwrP+0Q3/OCLl8Ns7mH3FMV7sPCVTp3UuFeT1TrTm0gYYoDuGkuPFfsFwc5rUZdbfOtc7Imjyp7Jj53qFmfPx3yIVn+Xhv+jBCWphTzhG2JbI8qSIp6t/vG1BUb9aBDNN774Ku/hvJomGO+4HSWHcWa88H8bUbjm5z5tJ35hMzetgfQ0OItJuQ/2BVmqf1igV1Mgn64auquTLL62lod5CkpWhPqtPg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: sure
      namespace: sure
