---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yavoo
  namespace: yavoo
spec:
  encryptedData:
    botToken: AgADfkXPvhQCsZbmBGvPWkU6WUwTIVNmAR8wZL75zz+3tE0Xyz4vW04Jzd3bJxaUpTJ0IRul62uy223eTWGl+VxvGeO6XcobdVNsxMGzK6gFS/84WHE5krK3UWoTRycRY0Rz1whZcQpKb1pra07zdPp8i6a7yXpjoG3otxEWrIWxSQ3ZV7Dr5wSql/kk0CtRCEhhsMYtFjpaGk4L9TVz9ioau63KMwp0BpLRRKljErILnmEb7IF6Fc2sninU1leHlnLO6hgk1snTE1pQjf10Ax9mgtQzAae5ZZcracVGRm4DBJwfX8X0dstA4v8LUt5qzQ4XM0vali0+4bloTjq9eByxOWOepnGSISCVQVM4K7WgzkFrHRAY8DZj7joAWPCVmjzooc5Fr2Ow0R8bcieZu7P42kGV1eyM5vcYLGJ1QGMx5D+oM9uFhzkmbXwRGvTV6zpWsWInUT8BTtXDfmQ4AKZc7qmxqnbGgLiDjK1esurpVgtnWkW3gVPh5xNdIoK3DJk60+ujIWx0KFs6jBmed4fV6aVbcKRP4EHQeBaCdQck7QOaD9Dr4z0eIL6jQE9tH61pacxOaMcBE3tHjdNdkvyx/iiCtsu6ALnwSfRzOFGbA5hAi0jQSdeEN0dQlFyYifhAKzKYvQP+7Qg0/8hP0xWKToE4bK0zZ3pw1Qb8oAMGQ9HiPZHkKv821of0pbtXNmT7qP7CDNCZYfxdngWWn9YxWgrDIv7iCl2sDhJa4bbXfLDKSky9p3eYTjE2Mbwx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yavoo
      namespace: yavoo
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yavoo-authsecret
  namespace: yavoo
spec:
  encryptedData:
    users: AgBKzv3drRmcUcuG4QAYJ6k87F4nDAmYwqJXGtp2WOR/eHEfB91hM0U2dyIur1oXSlTgxPOSdIiayszwcd0sIipEQJEgnjnBUh8nd3bGUwHrgoadFA0w/mCVuXvrgUlHfmhVAsAjDkQnDYKBQ980gxmf/8xioz3zv62QWfyGLwqsqcYLjNf5VjdC6lnWRM0zMb5ieI27cFgxhuUETJIfwPUdQylcNYulwulMXA81raSq+2o5MDbcCm0VOHg52GpN5pHkZFDuN2jNofJDRboaitBZh1RkRtM1vzsAghB9d5rFJvXV3x9bagvVvG7rznNeZqPSmapv2JDmr5qXDpa46o7Ag/vtjb7N+z2MptZdoE8G8qIYnUUHm5StdWq9/UyyowGrtDpVKr3MNiMLrn/XAvyUzi3AC5LxzZZzd7/E/B13m4dxQKnK9W3rgfa8xjo9g8iLOpE1s3Q/RipTxxA0ZEsLAimhwP5kQhubec+MXET9P0Yb8/EBR8eFsVmJEWlPXK8eM/qLObvOgw+KjteFgnEgOL8PZtmsDCr0Lu6A99W9N5Py8o32gXLhPXUy3j1BSr07DbU0XdpV5zUcmiOWbjHc/OmhsxyIRbA6Idamv7SuMBR53qwEW/VCXuHaTIYCvFj3svjb0/s+ekJGV/6EU2v2bq4Gqae4RrAv9GOIV9fPbCndwGB1BtRpu2Y80exxFOaGo4N7acjpK5xeOxmk2U/a2fGenmEbuwT8EIkKh9Th7hRsqLEscSdFnNTouKI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yavoo-authsecret
      namespace: yavoo
