apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: "@every 72h"
  name: homeassistant
  namespace: aya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - image: homeassistant/home-assistant:latest
          name: homeassistant
          ports:
            - containerPort: 8123
              name: homeassistant
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
      volumes:
        - name: config
          nfs:
            server: 100.72.0.34
            path: /docker/aya-homeassistant/
      nodeSelector:
        svccontroller.k3s.cattle.io/lbpool: aya
      tolerations:
        - {key: dedicated, operator: Equal, value: media, effect: NoSchedule}

---
kind: Service
apiVersion: v1
metadata:
  name: homeassistant
  namespace: aya
  labels:
    svccontroller.k3s.cattle.io/lbpool: aya
spec:
  type: LoadBalancer

  selector:
    app: homeassistant

  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: homeassistant

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: aya
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: home-aya.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant
                port:
                  number: 8123
  tls:
    - hosts:
        - home-aya.${BASE_DOMAIN}
      secretName: home-aya.${BASE_DOMAIN}

---