---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: aya
  namespace: aya
spec:
  encryptedData:
    hyperionPassword: AgA3kypspZo4cvYY+KBzz5j+eWpn50MeGzB0tO0nIVg9gCEd6yHjnUYyD8M4A0BjLiH2b6FqjvLKUMMpYyu3Id/A4tT9tLm8dVtGt01zNtkcBP7ovPGdnZWHichVgSjX3u665zzeVrCNzFpVBMmqfQ2csJl6cnU72dWFVqSWgdB+UNB5DYyL6TfiF4wrqtVKAODlehHv/2jCNupJjX4nO3H+jhiHPtQ30tIVDG6IV04hWgT0u6z70nlqcDlQ/Fmy+RmDYNySo7/fA7SrSMIi+JSxqenUBJuz0dwNnXda4cndJDmM/YLAxmla0UJgnHqwU/Y57RboU/qRc1YKjjkjNMX/H0NVR/1rIeLWA5WMAY2q/7qsK0n2Ux8qnaHOwDGUCwQ3J7sbMbTgjQ6DADUlmp0k61Qo4e2OQaGvu9JJBxZP81iEoT4+H4Nq4MTYsQ5Pb2FcCUAQUiNWDK9Jm48hYmUFofcL4amw9lL7XlIP8rJAGCN+Jh34WJLf7ItfV8ZBSktYlOS4bKudfRSppKZmW+ZrTiV8wzMjtgCE1s/8YJejepVR5B+mHMD2cseLJKqPVcQYWo3CczAlBH8oE91NuShnpCpl1Zle5vF460TgtkIYAAGkzlc0435u7ewjOjfEyY/bblAfVSUHS4pm33oX2TZTnsqh3NZY55pN+a8ayHpcNni2etHLtWHt/oIFp2cdfQHU2qZ10JQpRNx/dGmpN3jY/ZUS2MVG3ZtI
    piholePassword: AgDipxr0TYgmzfj4b6OBqTrVfp1jUzCH3xAFcI44xMRUFrauVGyjSHdV44QLKUCqFL31aJMnmvTQmGO/obBYi8uiQYTCuQseNbSmYQ8yBKLzHyLTdrv4fFzysiaw4SYw7g3BrYEEcEAyI9i4OBl4hEue6jUdafLNnZMl9Yxar168gfd5PxN+eaHFOfL5SllP3lLvl1VSaR/dEps8oGWNJckJe48/ksuSoP8D+srmREM18ml3Pu8eqJxLhQ5+QpK/B+e/SsKTtQL46WFTdVvZF8VNyhnUo+mufyp/6sdO0/efvNoWar9VriQGPwFkC+txKXakyS5NOaKiPYR728lNvQT9xqIz50DbbCdccODC7n3FvQapgdsYk9DqOJa8V2MYaVAN/ZCbv0L8xQp4R8xGfZ1eu/HqgwtFHYbpcCn3fSttvNaOf+0Yvg2VhLF5H+a+m38C/u9BtHX7jP7pYkrJxFjx/gmdXKrri4i27fMw81w8wvWOpazCX0W2fd63d0t3tdFtSnwiGwPMBbZjIOI6nPgKejt5hZnYw31HXuC2RcPX2JE2ePNQOuLQygTkCL76+HP4Gk3Lr/+jMiE9x4mt0xTs1dNoeZ+O3UxUGpBistD31rKiYYCmuBVQ3v5xwBzZyNcyalornUOCmj+jLSdE5tMQi06gHdN+2A7XrvJ6dfm3KziVkPMRi0Zp4FjIy4z3OycqRcZwAsGSmKF4tVpQnBax39+o7tfciIL4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: aya
      namespace: aya
    type: Opaque
