---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: aya
  namespace: aya
spec:
  encryptedData:
    piholePassword: AgDipxr0TYgmzfj4b6OBqTrVfp1jUzCH3xAFcI44xMRUFrauVGyjSHdV44QLKUCqFL31aJMnmvTQmGO/obBYi8uiQYTCuQseNbSmYQ8yBKLzHyLTdrv4fFzysiaw4SYw7g3BrYEEcEAyI9i4OBl4hEue6jUdafLNnZMl9Yxar168gfd5PxN+eaHFOfL5SllP3lLvl1VSaR/dEps8oGWNJckJe48/ksuSoP8D+srmREM18ml3Pu8eqJxLhQ5+QpK/B+e/SsKTtQL46WFTdVvZF8VNyhnUo+mufyp/6sdO0/efvNoWar9VriQGPwFkC+txKXakyS5NOaKiPYR728lNvQT9xqIz50DbbCdccODC7n3FvQapgdsYk9DqOJa8V2MYaVAN/ZCbv0L8xQp4R8xGfZ1eu/HqgwtFHYbpcCn3fSttvNaOf+0Yvg2VhLF5H+a+m38C/u9BtHX7jP7pYkrJxFjx/gmdXKrri4i27fMw81w8wvWOpazCX0W2fd63d0t3tdFtSnwiGwPMBbZjIOI6nPgKejt5hZnYw31HXuC2RcPX2JE2ePNQOuLQygTkCL76+HP4Gk3Lr/+jMiE9x4mt0xTs1dNoeZ+O3UxUGpBistD31rKiYYCmuBVQ3v5xwBzZyNcyalornUOCmj+jLSdE5tMQi06gHdN+2A7XrvJ6dfm3KziVkPMRi0Zp4FjIy4z3OycqRcZwAsGSmKF4tVpQnBax39+o7tfciIL4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: aya
      namespace: aya
    type: Opaque
