#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────

# Creates OVH API credentials limited to the adriangonzalezbarbosa.eu DNS zone,
# checks them against the API, and stores them encrypted with agenix in
# ~/dotfiles/nix/secrets/ovh-dns-adriangonzalezbarbosa.age. Nothing is written
# in plaintext and no value is echoed.

TOTAL_STAGES=3
ZONE="adriangonzalezbarbosa.eu"
OVH_API="https://eu.api.ovh.com/1.0"
SECRETS_DIR="$HOME/dotfiles/nix/secrets"
AGE_FILE="ovh-dns-adriangonzalezbarbosa.age"

# ovh_get PATH: signed GET against the OVH API, prints the HTTP status code.
ovh_get() {
  local url="$OVH_API$1" ts sig
  ts=$(curl -s "$OVH_API/auth/time")
  sig="\$1\$$(printf '%s+%s+GET+%s++%s' "$OVH_APPLICATION_SECRET" "$OVH_CONSUMER_KEY" "$url" "$ts" | sha1sum | cut -d' ' -f1)"
  curl -s -o /dev/null -w '%{http_code}' \
    -H "X-Ovh-Application: $OVH_APPLICATION_KEY" -H "X-Ovh-Consumer: $OVH_CONSUMER_KEY" \
    -H "X-Ovh-Timestamp: $ts" -H "X-Ovh-Signature: $sig" "$url"
}

banner "OVH: credenciales DNS para $ZONE"

stage "Crear el token en OVH"
say "Vamos a crear unas credenciales de API que SOLO pueden tocar la zona DNS"
say "$ZONE. Las usará cert-manager para el certificado de sure.$ZONE."
open_url "https://eu.api.ovh.com/createToken/?GET=/domain/zone/$ZONE&GET=/domain/zone/$ZONE/*&POST=/domain/zone/$ZONE/*&PUT=/domain/zone/$ZONE/*&DELETE=/domain/zone/$ZONE/*"
step "Inicia sesión con tu cuenta OVH (la que tiene el dominio)."
step "Script name: cert-manager-lamg · Description: DNS-01 y registros de $ZONE"
step "Validity: Unlimited."
step "Comprueba que los Rights son GET/POST/PUT/DELETE sobre /domain/zone/$ZONE/* (y GET sobre /domain/zone/$ZONE)."
note "Si la página no rellenó los permisos, añádelos a mano tal cual."
step "Pulsa Create keys. OVH enseña Application key, Application secret y Consumer key UNA sola vez."
ask_secret OVH_APPLICATION_KEY "Pega la Application key:"
ask_secret OVH_APPLICATION_SECRET "Pega la Application secret:"
ask_secret OVH_CONSUMER_KEY "Pega la Consumer key:"
[[ -n "$OVH_APPLICATION_KEY" && -n "$OVH_APPLICATION_SECRET" && -n "$OVH_CONSUMER_KEY" ]] || { warn "Falta algún valor; vuelve a ejecutar el asistente."; exit 1; }

stage "Comprobar las credenciales"
say "Llamo a la API de OVH firmando con lo que has pegado (no se muestra nada)."
zone_code=$(ovh_get "/domain/zone/$ZONE")
records_code=$(ovh_get "/domain/zone/$ZONE/record?subDomain=sure")
say "GET /domain/zone/$ZONE → $zone_code"
say "GET /domain/zone/$ZONE/record → $records_code"
if [[ "$zone_code" != "200" || "$records_code" != "200" ]]; then
  warn "OVH no las acepta (403 = faltan permisos o sin validar; 400/401 = clave mal pegada)."
  warn "No se ha guardado nada. Revisa el token en OVH y vuelve a ejecutar."
  exit 1
fi
printf '  %s✓ credenciales válidas para %s%s\n' "$GREEN" "$ZONE" "$RESET"
pause "Enter para guardarlas cifradas"

stage "Guardar cifrado con agenix"
say "Destino: $SECRETS_DIR/$AGE_FILE (la entrada ya está en secrets.nix)."
if [[ -f "$SECRETS_DIR/$AGE_FILE" ]]; then
  confirm "Ya existe $AGE_FILE. ¿Sobrescribirlo?" || { warn "Cancelado; no se ha tocado nada."; exit 1; }
  rm -f "$SECRETS_DIR/$AGE_FILE"
fi
( cd "$SECRETS_DIR" && printf 'OVH_ENDPOINT=ovh-eu\nOVH_APPLICATION_KEY=%s\nOVH_APPLICATION_SECRET=%s\nOVH_CONSUMER_KEY=%s\n' \
    "$OVH_APPLICATION_KEY" "$OVH_APPLICATION_SECRET" "$OVH_CONSUMER_KEY" | agenix -e "$AGE_FILE" )
if ( cd "$SECRETS_DIR" && agenix -d "$AGE_FILE" | grep -q "^OVH_CONSUMER_KEY=$OVH_CONSUMER_KEY$" ); then
  printf '  %s✓ guardado y verificado%s %s\n' "$GREEN" "$RESET" "$SECRETS_DIR/$AGE_FILE"
else
  warn "No pude verificar el fichero cifrado; avisa a Claude."; exit 1
fi
note "Dile a Claude que ya está: él monta cert-manager-webhook-ovh, el registro sure y el https."

finish
