#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

CTX="lamg"
NS="piracy"
SECRET_NAME="romm"
SEALED_FILE="deployments/piracy/sealedsecrets.yaml"
MANIFEST="deployments/piracy/romm.yaml"

banner "Claves de metadata para RomM"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Comprobaciones previas"
say "Antes de tocar nada, que estén las herramientas y el fichero a mano."
FALTA=0
for cmd in kubectl kubeseal python3; do
  if command -v "$cmd" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$cmd"
  else
    warn "$cmd no está instalado"; FALTA=1
  fi
done
if kubectl config get-contexts "$CTX" >/dev/null 2>&1; then
  printf '  %s✓%s contexto kubectl "%s"\n' "$GREEN" "$RESET" "$CTX"
else
  warn "no existe el contexto kubectl \"$CTX\""; FALTA=1
fi
# kubeseal habla con el Service, no con el Deployment: comprobar el que importa
if kubectl --context="$CTX" -n kube-system get svc sealed-secrets-controller >/dev/null 2>&1; then
  printf '  %s✓%s service sealed-secrets-controller en kube-system\n' "$GREEN" "$RESET"
else
  warn "no encuentro el service sealed-secrets-controller en kube-system"; FALTA=1
fi
if [[ -f "$SEALED_FILE" ]] && grep -q "name: ${SECRET_NAME}$" "$SEALED_FILE"; then
  printf '  %s✓%s SealedSecret "%s" en %s\n' "$GREEN" "$RESET" "$SECRET_NAME" "$SEALED_FILE"
else
  warn "no encuentro el SealedSecret \"$SECRET_NAME\" en $SEALED_FILE"
  note "lánzalo desde la raíz del repo agonbar-kubernetes"; FALTA=1
fi
[[ "$FALTA" -eq 1 ]] && { printf '\n'; warn "arregla lo de arriba y vuelve a lanzarlo"; exit 1; }
printf '\n'
note "Hoy RomM solo identifica por hash (Hasheous). Eso le dice QUÉ juego es"
note "cada fichero, pero no trae ni carátula ni ficha, y el plugin de Playnite"
note "ni arranca sin IGDB. Eso es lo que venimos a arreglar."
pause "Seguimos?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "IGDB: crear la aplicación en Twitch"
say "IGDB es de Twitch, así que las claves salen de la consola de desarrollador"
say "de Twitch. Necesitas 2FA activo en la cuenta o no te deja registrar apps."
printf '\n'
note "Es el proveedor que más falta hace: sin él no hay fichas y el plugin de"
note "Playnite ni arranca. Pero puedes saltarlo y volver a lanzar esto luego:"
note "el wizard añade solo las claves que le des y respeta las que ya estén."
printf '\n'
IGDB_CLIENT_ID=""; IGDB_CLIENT_SECRET=""
if ! confirm "¿Configuramos IGDB?"; then
  note "saltado"
else
open_url "https://dev.twitch.tv/console/apps/create"
printf '\n'
step "Name: algo reconocible, por ejemplo romm-lamg. Tiene que ser único en"
step "  todo Twitch, así que si se queja, añádele algo."
step "OAuth Redirect URLs: pon http://localhost. RomM no lo usa (habla por"
step "  client credentials), pero el formulario lo exige."
step "Category: Application Integration."
step "Client Type: Confidential."
step "Dale a «Create», y luego a «Manage» en la app que acabas de crear."
printf '\n'
pause "Cuando estés en la pantalla de Manage, dale a Enter"
printf '\n'
step "Copia el Client ID que se ve en esa pantalla."
ask IGDB_CLIENT_ID "Pega el Client ID:"
[[ -z "${IGDB_CLIENT_ID:-}" ]] && { warn "hace falta el Client ID"; exit 1; }
printf '\n'
step "Dale a «New Secret» y confirma. El secreto se enseña UNA vez."
warn "Si cierras la pantalla sin copiarlo, no se recupera: hay que generar otro."
ask_secret IGDB_CLIENT_SECRET "Pega el Client Secret (no se verá al escribir):"
[[ -z "${IGDB_CLIENT_SECRET:-}" ]] && { warn "hace falta el Client Secret"; exit 1; }
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "ScreenScraper: cuenta de usuario"
say "Opcional, pero es el proveedor que mejor cubre las ediciones españolas,"
say "que es justo lo que scan.priority.region está configurado para preferir."
printf '\n'
note "La imagen de RomM ya trae credenciales de desarrollador, así que"
note "ScreenScraper funciona sin esto. Tu cuenta solo sube el límite de"
note "peticiones por hora, que en un escaneo grande se nota."
printf '\n'
SS_USER=""; SS_PASSWORD=""
if confirm "¿Configuramos ScreenScraper?"; then
  open_url "https://www.screenscraper.fr/membreinscription.php"
  printf '\n'
  step "Regístrate (o entra si ya tienes cuenta)."
  step "Usa el nombre de usuario, no el email: RomM manda el login tal cual."
  printf '\n'
  pause "Cuando tengas la cuenta lista, dale a Enter"
  ask SS_USER "Usuario de ScreenScraper:"
  ask_secret SS_PASSWORD "Contraseña de ScreenScraper:"
else
  note "saltado; RomM seguirá usando las credenciales de desarrollador"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "RetroAchievements: API key"
say "Trae los logros por juego y el progreso. RomM solo necesita la API key,"
say "no el usuario."
printf '\n'
RA_KEY=""
if confirm "¿Configuramos RetroAchievements?"; then
  open_url "https://retroachievements.org/settings"
  printf '\n'
  step "Entra con tu cuenta y baja hasta la sección «Keys»."
  step "Copia el valor de «Web API Key». No es la de conexión."
  printf '\n'
  ask_secret RA_KEY "Pega la Web API Key (no se verá al escribir):"
  [[ -z "${RA_KEY:-}" ]] && { warn "no has pegado nada"; exit 1; }
else
  note "saltado"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "SteamGridDB: API key"
say "Da grids y heroes: el arte que enseñan Playnite y Big Picture en los"
say "accesos directos. No cambia nada en la web de RomM, solo en el salón."
printf '\n'
SGDB_KEY=""
if confirm "¿Configuramos SteamGridDB?"; then
  open_url "https://www.steamgriddb.com/profile/preferences/api"
  printf '\n'
  step "Entra con tu cuenta de Steam."
  step "En «API» dale a generar la clave si no tienes ninguna, y cópiala."
  printf '\n'
  ask_secret SGDB_KEY "Pega la API key (no se verá al escribir):"
  [[ -z "${SGDB_KEY:-}" ]] && { warn "no has pegado nada"; exit 1; }
else
  note "saltado"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Sellar las claves"
say "Se cifran aquí, en tu máquina, con la clave pública del cluster. En claro"
say "no se escriben en disco ni salen por pantalla en ningún momento."
printf '\n'
umask 077
# --scope cluster-wide tiene que coincidir con la anotación que ya lleva el
# SealedSecret piracy/romm. Si no coincide, el controlador no lo descifra y el
# fallo aparece al sincronizar ArgoCD, no aquí.
sellar() {
  printf '%s' "$2" | kubeseal --context "$CTX" \
    --controller-name sealed-secrets-controller \
    --controller-namespace kube-system \
    --scope cluster-wide --raw --from-file=/dev/stdin 2>/tmp/kubeseal-$1.err
}
declare -A NUEVAS=()
if [[ -n "$IGDB_CLIENT_ID" ]]; then
  NUEVAS[igdb-client-id]="$(sellar igdb-id "$IGDB_CLIENT_ID")"
  NUEVAS[igdb-client-secret]="$(sellar igdb-secret "$IGDB_CLIENT_SECRET")"
fi
if [[ -n "$SS_USER" ]]; then
  NUEVAS[screenscraper-user]="$(sellar ss-user "$SS_USER")"
  NUEVAS[screenscraper-password]="$(sellar ss-pass "$SS_PASSWORD")"
fi
if [[ -n "$RA_KEY" ]]; then
  NUEVAS[retroachievements-api-key]="$(sellar ra-key "$RA_KEY")"
fi
if [[ -n "$SGDB_KEY" ]]; then
  NUEVAS[steamgriddb-api-key]="$(sellar sgdb-key "$SGDB_KEY")"
fi
unset IGDB_CLIENT_SECRET SS_PASSWORD RA_KEY SGDB_KEY
if [[ "${#NUEVAS[@]}" -eq 0 ]]; then
  warn "no has configurado ningún proveedor; no hay nada que sellar"; exit 0
fi
for k in "${!NUEVAS[@]}"; do
  if [[ -z "${NUEVAS[$k]}" ]]; then
    warn "el sellado de $k salió vacío"; cat /tmp/kubeseal-*.err 2>/dev/null | head -3; exit 1
  fi
done
printf '  %s✓%s %s valor(es) cifrado(s)\n' "$GREEN" "$RESET" "${#NUEVAS[@]}"
printf '\n'
# Las claves se insertan en el encryptedData del SealedSecret que ya existe.
# El controlador reconstruye el Secret con todas, así que db-password y
# auth-secret-key siguen intactas sin volver a sellarlas.
# Los pares van como argumentos, no por stdin: stdin ya lo ocupa el heredoc que
# le pasa el script a python, y usar los dos silencia el script y hace que
# python intente ejecutar los datos.
PARES=()
for k in "${!NUEVAS[@]}"; do PARES+=("${k}=${NUEVAS[$k]}"); done
python3 - "$SEALED_FILE" "$SECRET_NAME" "${PARES[@]}" <<'PY'
import sys, re
path, name = sys.argv[1], sys.argv[2]
nuevas = dict(a.split("=", 1) for a in sys.argv[3:] if "=" in a)
doc = open(path).read()
docs = doc.split("\n---\n")
hit = [i for i, d in enumerate(docs) if re.search(rf"^\s*name: {re.escape(name)}$", d, re.M)]
if len(hit) != 1:
    sys.exit(f"esperaba 1 SealedSecret llamado {name}, encontrados {len(hit)}")
d = docs[hit[0]]
m = re.search(r"^(\s+)encryptedData:\n", d, re.M)
if not m:
    sys.exit("ese SealedSecret no tiene encryptedData")
ind = m.group(1) + "  "
for k, v in nuevas.items():
    d = re.sub(rf"^{ind}{re.escape(k)}: .*\n", "", d, flags=re.M)   # reemplaza si ya estaba
    d = d[:m.end()] + f"{ind}{k}: {v}\n" + d[m.end():]
docs[hit[0]] = d
open(path, "w").write("\n---\n".join(docs))
print(f"  insertadas {len(nuevas)} clave(s) en {path}")
PY
printf '\n'
if kubectl --context "$CTX" apply --dry-run=client -f "$SEALED_FILE" >/dev/null 2>&1; then
  printf '  %s✓%s %s sigue siendo YAML válido\n' "$GREEN" "$RESET" "$SEALED_FILE"
else
  warn "el fichero quedó inválido; revísalo con git diff antes de nada"; exit 1
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Desplegar"
say "El deployment ya referencia estas claves como optional, así que lo"
say "único que falta es que ArgoCD se lleve el SealedSecret y reiniciar el pod"
say "para que RomM lea las variables nuevas."
printf '\n'
git --no-pager diff --stat -- "$SEALED_FILE" "$MANIFEST" 2>/dev/null || true
printf '\n'
warn "ArgoCD sincroniza deployments/piracy solo, así que el push despliega."
if confirm "¿Commit y push ahora?"; then
  # El mensaje nombra lo que se selló de verdad. Antes iba fijo a "IGDB and
  # ScreenScraper" y mentía en cuanto saltabas alguna fase.
  QUE=$(printf '%s\n' "${!NUEVAS[@]}" | sed 's/-[a-z-]*$//' | sort -u | paste -sd, -)
  git add "$SEALED_FILE" "$MANIFEST"
  git commit -q -m "piracy: add RomM metadata credentials (${QUE})" || true
  git push && printf '  %s✓%s pusheado\n' "$GREEN" "$RESET"
  printf '\n'
  # Sin esto la espera de abajo caduca casi siempre: este cluster reconcilia
  # cada hora, así que ArgoCD puede tardar eso en ver el commit. Se queda en
  # "Synced" contra la revisión vieja, que es lo que despista.
  say "Forzando el refresco de ArgoCD..."
  if kubectl --context "$CTX" -n argocd patch application piracy --type merge \
       -p '{"metadata":{"annotations":{"argocd.argoproj.io/refresh":"hard"}}}' >/dev/null 2>&1; then
    printf '  %s✓%s refresco pedido\n' "$GREEN" "$RESET"
  else
    warn "no pude refrescar la Application; puede tardar hasta una hora"
  fi
  printf '\n'
  say "Esperando a que el Secret tenga las claves nuevas..."
  UNA=$(printf '%s\n' "${!NUEVAS[@]}" | head -1)
  for _ in $(seq 1 20); do
    if kubectl --context "$CTX" -n "$NS" get secret "$SECRET_NAME" \
         -o "jsonpath={.data.$UNA}" 2>/dev/null | grep -q .; then
      printf '  %s✓%s el controlador ya descifró %s\n' "$GREEN" "$RESET" "$UNA"
      kubectl --context "$CTX" -n "$NS" rollout restart deploy/romm >/dev/null
      kubectl --context "$CTX" -n "$NS" rollout status deploy/romm --timeout=180s
      break
    fi
    sleep 15
  done
  printf '\n'
  say "Comprueba que RomM los ve:"
  note "curl -s https://romm.\${BASE_DOMAIN}/api/heartbeat | jq .METADATA_SOURCES"
else
  note "sin pushear; los cambios están en el working tree"
  note "revísalos con: git diff -- $SEALED_FILE $MANIFEST"
fi

finish
