#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

CTX="lamg"
SECRET_NAME="repo-github-agonbar-kubernetes"
REPO_URL="https://github.com/agonbar/agonbar-kubernetes.git"
OUT="/tmp/repo-cred-sealed.yaml"

banner "Token de GitHub para ArgoCD"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Comprobaciones previas"
say "Antes de tocar nada, que estén las herramientas y el cluster a mano."
FALTA=0
if kubectl config get-contexts "$CTX" >/dev/null 2>&1; then
  printf '  %s✓%s contexto kubectl "%s"\n' "$GREEN" "$RESET" "$CTX"
else
  warn "no existe el contexto kubectl \"$CTX\""; FALTA=1
fi
if command -v kubeseal >/dev/null 2>&1; then
  printf '  %s✓%s kubeseal %s\n' "$GREEN" "$RESET" "$(kubeseal --version 2>&1 | head -1)"
else
  warn "kubeseal no está instalado"; FALTA=1
fi
# kubeseal habla con el Service, no con el Deployment: comprobar el que importa
if kubectl --context="$CTX" -n kube-system get svc sealed-secrets-controller >/dev/null 2>&1; then
  printf '  %s✓%s service sealed-secrets-controller en kube-system\n' "$GREEN" "$RESET"
else
  warn "no encuentro el service sealed-secrets-controller en kube-system"; FALTA=1
fi
ACTUAL=$(kubectl config current-context 2>/dev/null || echo "?")
if [[ "$ACTUAL" != "$CTX" ]]; then
  note "tu contexto por defecto es \"$ACTUAL\", no \"$CTX\"; el sellado fuerza $CTX"
fi
if [[ "$FALTA" -eq 1 ]]; then
  printf '\n'; warn "arregla lo de arriba y vuelve a lanzarlo"; exit 1
fi
printf '\n'
note "Contexto: el argocd-repo-server corre en ovh02, IP de datacenter de OVH."
note "GitHub estrangula el git anónimo desde ahí: 2 de 10 intentos funcionan, y"
note "repos ajenos como kubernetes/kubernetes fallan igual, así que es la IP."
note "Autenticarse quita el estrangulamiento. Eso es lo que vamos a montar."
pause "Seguimos?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Crear el token en GitHub"
say "Necesitas un token de solo lectura. El repo es público, así que no hace"
say "falta darle acceso a ningún repositorio concreto ni ningún permiso de"
say "escritura: con leer repos públicos basta para quitarse el límite."
printf '\n'
open_url "https://github.com/settings/personal-access-tokens/new"
printf '\n'
step "Token name: pon algo reconocible, por ejemplo argocd-lamg."
step "Resource owner: tu propia cuenta."
step "Expiration: lo que quieras. Lee el aviso de abajo antes de elegir."
step "Repository access: marca «Public Repositories (read-only)»."
step "Permissions: no toques nada, no hace falta ninguno."
step "Dale a «Generate token» y copia el valor que sale (empieza por github_pat_)."
printf '\n'
warn "Cuando caduque, ArgoCD NO dirá que el token expiró: volverá al camino"
warn "anónimo estrangulado y el síntoma será otra vez «could not read Username"
warn "for https://github.com», que no se parece nada a su causa. Apúntate la fecha."
printf '\n'
pause "Cuando tengas el token copiado, dale a Enter"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Sellar el token"
say "El token se cifra aquí, en tu máquina, con la clave pública del cluster."
say "En claro no se escribe en disco ni sale por pantalla en ningún momento."
printf '\n'
ask GH_USER "Tu usuario de GitHub:"
if [[ -z "${GH_USER:-}" ]]; then warn "hace falta el usuario"; exit 1; fi
ask_secret GH_TOKEN "Pega el token (no se verá al escribir):"
if [[ -z "${GH_TOKEN:-}" ]]; then warn "no has pegado nada"; exit 1; fi
case "$GH_TOKEN" in
  github_pat_*|ghp_*) : ;;
  *) warn "eso no parece un token de GitHub, pero sigo si tú lo dices"
     confirm "Continuar igualmente?" || exit 1 ;;
esac
printf '\n'
# La etiqueta argocd.argoproj.io/secret-type: repository es lo que hace que
# ArgoCD mire este Secret. Sin ella el Secret existe y no sirve para nada, que
# es el error clásico aquí. kubeseal la arrastra a spec.template.metadata.
umask 077
# --context es obligatorio, no opcional: kubeseal usa el contexto por defecto de
# kubectl, que en esta máquina es un cluster de GKE distinto. Sin él, el token se
# cifra con la clave pública del cluster equivocado y sale un blob que el
# controlador de lamg no puede descifrar nunca. Falla en el apply, no aquí.
if cat <<EOF | kubeseal --context "$CTX" \
                        --controller-name sealed-secrets-controller \
                        --controller-namespace kube-system \
                        --format yaml > "$OUT" 2>/tmp/kubeseal.err
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: ${REPO_URL}
  username: "${GH_USER}"
  password: "${GH_TOKEN}"
EOF
then
  unset GH_TOKEN
  if grep -q "encryptedData" "$OUT" && grep -q "argocd.argoproj.io/secret-type" "$OUT"; then
    printf '  %s✓ sellado%s → %s\n' "$GREEN" "$RESET" "$OUT"
    note "$(wc -l < "$OUT") líneas, con la etiqueta de repositorio dentro"
  else
    warn "el fichero salió pero le falta encryptedData o la etiqueta; no lo uses"
    exit 1
  fi
else
  unset GH_TOKEN
  warn "kubeseal falló:"; sed 's/^/    /' /tmp/kubeseal.err | head -5
  rm -f "$OUT"
  exit 1
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Entregarlo"
say "Ya está. El blob sellado solo lo puede descifrar el controlador del"
say "cluster, así que es seguro pasarlo por chat, commitearlo y dejarlo en git."
printf '\n'
step "Dile a Claude que el fichero está en: $OUT"
step "Él lo mete en system/argocd/sealedsecrets.yaml, commitea y sincroniza."
printf '\n'
note "Después, la comprobación de que ha funcionado (ahora da ~2 de 10):"
note "  kubectl --context=$CTX -n argocd exec deploy/argocd-repo-server \\"
note "    -c argocd-repo-server -- sh -c 'ok=0;ko=0;for i in \$(seq 1 10); do"
note "    GIT_TERMINAL_PROMPT=0 git ls-remote $REPO_URL HEAD >/dev/null 2>&1 &&"
note "    ok=\$((ok+1)) || ko=\$((ko+1)); done; echo \"\$ok ok / \$ko fallos\"'"
printf '\n'
warn "Borra el token del portapapeles si lo tienes ahí."
pause "Enter para terminar"

finish
note "sellado en $OUT, listo para commitear"
