---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-cmp-values
  namespace: argocd
spec:
  encryptedData:
    AMANDA_DOMAIN: AgB32KGPsCrfFA2r0m0jTh9Gh2puiUYzwUYINNvPg1IPZD6RIyByIWG1yG6zJ7UrOllDiNEKvgqlkAkFlAhP1uPkquO+vw2athA5P06j6kp8PnGOEZsnQ4WNzbj1VVC2UbliZhAucKaQeZbidwPaqnhdZzKFYMQqxksoC61xtHssxm7xS0xgdoX4XilTf3tnT0ie/HO9wUFiY3aNA/yLzpdEeTxf9WDdgKlJg1qHu6lvMSRRN/i08G3Wk66u4tBueJGFJPJxe8gffSg3RmUERnXURrO4xox4KDcBOad6srNjfS9+LNsar8/2YM6Tgwi4Dx1RO8heutcQiPc1WQPWLIjmtH9gzkkrM9bOLbZby7YkgSed4Ft0XlwF7QLCILUVlquhpluydt8VM4VYaVX37s72cawI661qaQmB5psdXzJ6JRzOTSpzibNsvOf3QJIRovb+Vdxo5tIykV5S076614qjfblPtRpnGrOYrcuBHQT1lfqTsDw58TPjxE2J+5v7B7nWGqwjxfg6LhxfrFyK4zORDs3shGxZiFbMkqtvhMWGh/27Hxh8x6ohn6V4O5maiNLEeL7R+WNo/Ulnx4Tz7NrrK782n00mgoj7Yh8loNejR9WKGyiEKNGZlLbgod0UBgBLu6GNHSz/AgbQin+YLS/azNFSD6eMLlQqNEtaPz7Mnzw6iQ/hweVUPPBQFXh8pdogJS2jADYnUtsMFFg=
    BASE_DOMAIN: AgCRRri4TJGNf3No+FVuXkq/c2fD2I0GOKsWgsG2rJcdjGd26ePADwfDY0qtsttwZ5O01+KswzCf+HkUdsJeoziWvnkL3UGdwEFX4/ct++OKI0iFzHw9Jf3nmlW0HYpp4VAxHwFbexMj5awEjhLLcyGR7eSmI/yo0UWwxlQMLrzx8WTbDYFdT2aLymFF86X63DsqjV6migAe5R3u80rJCTRcRrrdIt+qNiQrHzD5pXkFfSSkVDAe4WDvclBxi15pV5ZVbdqF8/zfGUU2agAhsWHQm7Gv1evgSvWcoWSpyMhxwkoNSf9zZEhfCveWMLYLuq3YTky3tQBOmHmBSKcyh4mXhtwHjDANUiFPVgvS1RO+h+2UpFZV8nqwkE82xQK6J6wo9698yNrqulx5nvtMcA7zhOec2RGA4H1RV9a+hCYSbtI7CzPFC9i9xjocL+OnI7+UN48p/76wwg5OMGieUlaIMkFSObuxzrCxanZx6hxWgjGy8lzRbyBIJlFKW0pTTX1WBoTBJN07dmwisw09fLmoyq9arUzpMHJeszrKr6glPxXXabjWFSBPAwisAVcEjXHILaHBWn1z2naaBKs2xSwiQlV7SlOhuzWLlVu6ULZjY0/8DOntb3EgPGGUMeYIEt7zGavvfJjpkAI6FVhZZC0/K/YCR51Qd0dSS0g471GnTFyBNMXaWTkhhFcggXwrRHkAzSp0PZIK5huDPOgmWCrzhliDz12z3/w=
    LETSENCRYPT_EMAIL: AgBv/3tTNKJNn6NPBAkfBvXBl/0QE9hyu9JrN3qPG57XHaVJnazPM+L7zI7IgHfgvNO+uHRkiZ7W7vY2FBWcaus8X7RLt4reuR4duzS6K8ugjEe04MsRVvQcUG3LOWCmTQ3EMhPVihEQ+JJqZ4eKJ95jBccrmAg9teFtkYtXR86Eqk8Ky9kqGLFjGJeX4dn7Ny8/FrOOsGqNgka9ORoTDCLnVOy+bSNFDJjqNHXiHmrOsgZXVi9UvOnMx6WkdWG0UpavyNnJyWF389JByiiXOKVl9kJTo/ZNx61mJG+X/Upd83srkKmUvUz1rcYfmvllxzAyAzhGeXIPL9BmXOJXHCAVXe0/Uq4SNuvjIw6RsWrX30XP19qEZUq82rMiX9ceAWjKJhmA5bcbSHqbYXe+YwMhY2gWSGsbmfS3JRLLmr3jSM+9lDLb0JdHXyaWgzs6HblVuHPuZqO+8f+p3q/KjVjeyGjsAPX2gtfEIeN7UuqXEO+zmUlBmlUI3zwVcJFCMaKCFmQvEnwsJdMlwDTbS+yT7kNefnbSa/MtgxyVXMq+39nMeLEsoQebOPkZllK5q15giFgG5CtTrWvdZgVdyuSkymIqwn+6py/c0AC7ysrv1CvDcc5sQcTNKrNsUeT02CxOdA0511ddfB+kzALMB+BCNrigARRzXkQImtFe0dh5Ph98iaBw1JIZyjyS/FFAuoDASVlCiIayhFQpbRat1byvqRxvsH3PiIcRccQgzKRYzyw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-cmp-values
      namespace: argocd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ghcr-pull
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCmI6z2JX2bizmWUrk0dfOFJBetoAekuiKWuFwXId94jDbD2vNFQaEaCrK+zBUbaYx4jTCH+Cr01qs9Uw/Rjep1goC8gX0P3523OhpLmxa46leNte5lXwtVEklIElwgVl9JmskLQc0rByVQSwrudEMZWKmSpjjdEH0FJsu9VWWwibON3KfKzEvfTClmaG4C3vj1jKFXJ1gEbn5Le+IIMXN11fTgFai6IL0fPU6yWSzfUdP4VU5HOPQDhhEF6rEnm31lwwkrWaPGCVSKdNF03gVmFAgD7joL0/MaZrChJgo5Bwr1M5D02EICRGRgxv4wRKMGThCTXnaT3T5+6axAOzVgM2fmhLpqsWMEtjTOrn+hAKeT9+GaI37X+q1Gy4o5CFpYRJhdyktTcPSTwoFBve7dsextmgAKDaKb7mGUdnGirQtbO4kpjd456axELOuJM/g8Up2zycsuSjlYam+kRvrGeLqir8SGWKdyvAkOSKYP6lrWREnwAc/jPFvRX006pFNxb1zuZ/wRSdLCD4Ji7wHnykUK/uUyBoFEfWCX8s802CbtNZkdi8x1OMUp+hrRdXYcRX2x8x6SGSIDUoUZWZ9uSEyF5w3O73VGhNVHJBnQ142m1mXnmzh3HOrvZWrrEoRB56X8ZsAutn6SosWDXzcT4QcO4d7bFqQWlTqilOwHIfj/AjcmnjlUfjkic2VCnEVaCPZMQ8RcF3jR6+ismXMxDzbuSC2ZTpIxfjgQCSqBXvLJlZsurY9cUb/F4BizJ8PhBVQQlsNcA1wsH+JjMUFzYmacIQm8LJH87BLAfBTcgyTGuKcQZfD4A7lTwyop1uNBlQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ghcr-pull
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
