---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-cmp-values
  namespace: argocd
spec:
  encryptedData:
    AMANDA_DOMAIN: AgAzBMsgDsBlOU2gErs7nBfHAIIgIIiKSrAgvpUOGTzSyRYUX1SIe4Fa9+bGyYS/axP/VIxE7T2VUl7zEy1a29KhWung32GRZP2vHcdJc12dPxsbBS7m42jMZeACQ6s6jrpdpIWVtI00fkeFDaYllrHJ+O3k5qEplPaGttvekkTIbrZ5MUS43VE/zRc1JYtdVU3uqn3rnnZriMxFAiwlsOXplf4w6HNIulubdWdx4XKVJPIYvMckWW4CtQhd7wKvxDH+M6ApITEUiouez0z4qIhX60UavGj++pSsjpHO3yakddvmcdhgdbpA9cl6uOjqpcDZCofFB5n/9iIHWjvQxfWcn5Z1gswsCvaiG7KhSIoCKWKdOXRRnfsygLa3kbDQa9WhDhlxZy5UDtkW00QsM5AE0nhFxuY6gZFVQ1OezTVCM8KaUWaCzVaFXWQGl1VWGq7rpH8/BbU5Z0ZsCENMmVjCGYCKryzBuSgJXcbicqIzgi1wrGp1L2BtRo+2GOoHpJZ4RlZKfrpEbyiGDgmmPwupYb+5G1PZ5Y2fe4oEUp4R1gEvWSVztiRQjHfHTc0VtAUu4z0gV5w9uZLHYG6/mtKLMz2TwHieo4T5Oa7CVl3wD01kRJhka6yhXik3cJY85Xvs4ktR8YzLi/NLUhx64evQTiSqlY+NWYCJgIjakvbZa/cbotRri8Ge2RM6hy9EE1n2nSp4/Ox7YZ3ZiXw=
    BASE_DOMAIN: AgBKe+keuPl/IoB2d1OapQJFGwUEqaN8txqqJ/o8vXOU/hacqhwfeoo1M6CoUanJuD/6PqSQ+uooYWVSb7uAK7NbnfZuuzCs4LY3UOrP3uMGwKab40Dr7MiVbnCxbd6DYXHsvuMWfWISUZLkFW3gpAsG3ciyGEdq0bKiRmG02Dv6irlJkUquT60sJc5TfadDX9aEMG2TOABt/eEjcxkPvQHTMjyB7ZNDZVe7ngGbNluT2BIax2OkQ6OkPONmebOrbt3GDKaljFah6uxeWNzmb98yttvJ2SyHl/57u6/VVBBVFDRCQGTn3kKv6KgWvzhcQk8oNz6ZgEIxzOcPGLhPuF4l9UgzUSe5SpmCKwwzFfSFf4/b2nCYJUcU24tLUBb60PWvSfOcYx08ESbkHb45wlcYFwD5ksLXw3EFI9aMI0lYwBZl6oJBVrRI3g4v9CgLtfXgBm0VemJrIJttOsKQu8R7QHnHZ/38IK/umsRSf6VGD+u9BP+DnEMhNK59W7hCicIv1F69nythWdh1yCTVADY0uMAy+HzboOfmFsmbbVyoKfNQG+AQxeddLZf1dG4CxjEM1B3CTnIov0P3YLiOsIjQSmuILFZvybRoWz08fupryFX9FuuDROSKO+yNA/N4oW1hvXYWQUiUWNcLsAFoubvjX7dbsOZKiMOJc9K4Cy4Q9igdjiIU/JOYfmYlQH7sTa+BDAXCt6atXRfS5RVqovNWgdoyX+gzQJg=
    LETSENCRYPT_EMAIL: AgDWZ6hFK8nhpiqwuNPCEboaZDq1Y/Ejp/5Vz46XJ3qSECH9m8XgxLGzp9xqCr0mlV5JPoYjejKkgjRxNwQcrQRNNiXWI5i+A1u9UTW+ceY52Th2FtnOGDRSvoGY39OQyBhG7Spca3XUONkmhdfj6bgoPbazaK3PLgPCMel4F9g7njYA+BR7kVrbrkMgFZ6Fyx5tlwt86yLSRjIXVDcitSIeZhJpziMdKe+xHi9JVSVsz9n43Fti9+qdP9l27UKufoALk4b2TgAuIf/Tp9fLNvXkUUNQ4lrgEmFURKpACO4/pCLkhk4YYFG4srGOZgteXUW9GeveFdv/qlJ1fZbis9pcIm67tji4W/DxDAqloxJ4kttIZ3gdcjN1wYHfKVXc7+Y3la16IOE/6DUGRBvgZhTKlmmun9hzM7WlWFmWqixn3AsxA4tAzonbq+npO+YMizVHiO2WzvaEf3+I/dzAIgd7Z1xBLC+82KLvHJT/N1jyt7hamA++tHl5lsxzeKX2rB//mgF+Bk38TTbRUBPzm9bQgNJACVGFA724MeupRxAfVIATVBYtbHCsZqPSD0PREtkCqsVyCnicTixPh/wosqNYlU7Y4+GgfyHcGDXHZ3DaV0KWl9rphBk6wrKyGWpVrl0tCa8Jyk+8uVgUkktN2oi0Yu7Q7fN9cGz4U0vRst9QTGT5LW7fF2MxcE7xrsW98QiKfC9txgg2VjkahfB6mi3/JAPjxL1Hi80BMIg3SzAJWbw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-cmp-values
      namespace: argocd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ghcr-pull
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgChFT7d/koKrmgDUPZ/d/9lUonLx8mnlayXA2+DQHL/8EJyNvUiBUbJlePzysphpAU+EcF4rWu/almRJ+NlA5cNvrjVNIGpZzS5NK5ZEUbDRX+djiWsOqCsKpzAUmA4gqZephuokp3OdqKIo0/c9WR4gm0umqLLxmXEBgyGiRViqHkCe+nyKpHUQCQKUCQcYe66hd26qSWAIF5qwgX3Tf5xpfFzlKO41FaOGSKyrtPyyknMy+WCecbWV2D7+wwLo2GK30rmA7QquuROH4ZRw55zweyhfQNe4kIU/IbEM4x6X7w8ZGn6/6RNAT+6NnUnDJS710UO0FXOEnRB4R3xSz+WSRv6iu8fRp7ldQqqaBV72V7RFPbSim/f3v0esNwcxzVmmMuceYhaOe3AdkKUc2pYCaRUHw3MPFAZUwDDcUb9jt61UslbMUIJ/+YrxK9r5/Xr+bITMLCcN3DgFM+SCIOPQzWWjXyB5JV1aPpEgF4AxXuzYCLuYIhszb3rJlPgMpnQSOfqB0Zfem0zp5b3A8nzhk/H4xixryDfMoQiOPZilSCpoJiZfrwKH2n+6IxsiX+/PHlCgJV0NUlOo1lDOYbb3ker0NQhAF3xGzgbEibFxcV9mij9DWIliCEl73yJOSYdV6RCcHZ4KemekqehbVDb6HwaP6KPBikSq8+9BLj+cmIaNuARqPBM1KL10OtOP3jM6dvZpmztFny8XxCBY2e/ttlwMCMC5sG2zUlR+xLEouS3dmIBqp+FwwDPe00JZTVJOtWgFFGqtf6H++KHlz7WmCm/rNKEmk6yeTdFGj0CYCCH75RfDOGipxxA8aIOQYhyXg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ghcr-pull
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
